### ISSUE TITLE
Research Improvement Proposal: SCRF Podcast

### ISSUE THREAD

**Issue by Coinproz** [smartcontractresearchforum/research_team#100]
Proposal document outlining an idea for a SCRF Podcast:

https://docs.google.com/document/d/1ABeW1keEKOUT8EAn2rYj4Yo6d5g9xfwOkR2-nLPT76o/edit?usp=sharing

**Comment by eleventh19** [comment]
We have been updating the linked podcast doc, have recorded our first interview, and are planning our first YouTube video pilot using that interview. Working on the production plan

**Comment by eleventh19** [comment]
The production plan for the pilot was approved and the process has been started

**Comment by ghettodev** [comment]
Can we tighten up that project plan linked in the description, lots of notes in there still. I'd like to post it to the repo.

**Comment by eleventh19** [comment]
Pilot episode is being edited/produced. Need to review and get another round of edits

**Comment by jamesmcgirk** [comment]
Providing production review notes during the process

**Comment by eleventh19** [comment]
[Pilot](https://www.youtube.com/watch?v=TsuiC-ue2z4) has been published. Added a governance specific video interview series [proposal doc](https://docs.google.com/document/d/1M0AN_yqew5PkNhjWMLjAi9crQbOCsp1SuV986VhZXdY/edit?usp=sharing), an overall governance+SCRF approach (#154), and will work on abstracting both to be applicable to any topic once these two are refined.

**Comment by eleventh19** [comment]
working on a [production plan](https://docs.google.com/document/d/1MPs0MQTtQX0SMnpGAIA99jjfwNVM7r2KIAp-th37PR4/edit#)

**Comment by eleventh19** [comment]
this is the current [governance brainstorming doc](https://docs.google.com/document/d/1zJfbgSvx9SNhkgGPQX2cBE_2P0jBy4siG_-nIdWahL0/edit#) exploring what specific problems to explore and who to feature

**Comment by eleventh19** [comment]
Here's the [folder](https://drive.google.com/drive/u/0/folders/1iKljbt1yJAnjLmfQV2XJQC-FenHjEwXP) where are saving info for the podcast. To have docs tagged in a single comment, here are some of the current docs being used
* [overall project plan](https://docs.google.com/document/d/1M0AN_yqew5PkNhjWMLjAi9crQbOCsp1SuV986VhZXdY/edit)
* [production plan](https://docs.google.com/document/d/1MPs0MQTtQX0SMnpGAIA99jjfwNVM7r2KIAp-th37PR4/edit#heading=h.gf97k642d496) 
* [governance brainstorming doc](https://docs.google.com/document/d/1zJfbgSvx9SNhkgGPQX2cBE_2P0jBy4siG_-nIdWahL0/edit#) (updated with draft eps for onboarding and treasury) 
* [notes doc](https://docs.google.com/document/d/1VmfwgPu3BkAvHW6LEuWrt1At7_E6f86aALH45of9gok/edit#)

**Comment by eleventh19** [comment]
Reviewed the brainstorming doc with @ghettodev and made some adjustments. going to review with others this week and then will proceed to start outreach

**Comment by virtualtart** [comment]
Developed [Workflow Doc](https://docs.google.com/document/d/1Sdi9w9SDX4gRQqJl2cSGa-jFe5FUwbd2ujpmxC3djWI/edit?usp=sharing) to match up production plan with document pipeline

**Comment by virtualtart** [comment]
Greenlit/finalized [Guest Checklist](https://docs.google.com/document/d/1Sdi9w9SDX4gRQqJl2cSGa-jFe5FUwbd2ujpmxC3djWI/edit?usp=sharing) for pre-production organization of interview guests

**Comment by eleventh19** [comment]
First two interviews (1.1 and 1.3 are scheduled). @jamesmcgirk is going to be helping with drafting the 'actionable takeaway' posts. I need to lock in the second guest of 1.2 and finalize the second mini-series

**Comment by eleventh19** [comment]
transitioning the project management of episode specific cards from the content pipeline to a beta of the new PM functionality, @ivanplazacic is creating the board. need to schedule two episodes. need to finalize 3 guests.

**Comment by eleventh19** [comment]
The first mini-series is out and the second mini-series is being [tracked here](https://docs.google.com/spreadsheets/d/1Z6cFrMwQvLohhVpxbMdBFBzyBUFim7nl1TDUAxFM0AA/edit#gid=238547836). We have to start planning the next mini-series 

I propose doing a series of highlights on web3 oriented research DAOs

**Comment by eleventh19** [comment]
The podcast is fully up and running. The next episode will be me interviewing Rich, then on art+blockchain, then a research summary highlight, then DeSci or DAOStarOne. I am going to close this card and will launch a new one for figuring out project management for the podcast going forward
