### ISSUE TITLE
Establish presentation layer of metrics for engagement team

### ISSUE THREAD

**Issue by visavishesh** [smartcontractresearchforum/research_team#102]
Description:

Resources:
[SCRF: Coverage Map & Metrics](https://docs.google.com/spreadsheets/d/1-ocDv4V1GvOIxQ2XvgTSBrEgN0ztbaczXczBhPnnj-E/edit#gid=1870266059)

**Comment by zubepaul** [comment]
The link to the spreadsheet has been added. Next step is to update the Description and how this document integrates with other processes.

**Comment by encore9870** [comment]
This ticket is no longer relevant. Let me know if we should not be closing it!
