### ISSUE TITLE
Project: ACM Digital Threats Special Edition Editing/PM

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#107]
### Project Description

This project is about helping create an ACM Digital Threats: Research and Practice Special Issue on blockchain. That would entail:
1) putting together a call for proposal
2) marketing to our network (and ACM does the same)
3) review submissions and peer review articles
4) publish issue
[Special Issue Editors.pdf](https://github.com/smartcontractresearchforum/research_team/files/6535311/Special.Issue.Editors.pdf)
[Examples of call for papers](https://dl.acm.org/journal/dtrap/calls-for-papers)

The benefit to SCRF is:
1) giving researchers we want to work with more a chance to publish some of their recent work (supporting outreach, new engagement opportunity, promotes research) 
2) provide SCRF a chance to create a follow up discussion to the issue on SCRF (drive additional engagement and content)
3) create more outreach opportunities to bring in more researchers 

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] create project doc
- [x] create process doc 
- [x] review the requirements and think through potential benefits
- [ ] decide if we want to do this
- [ ] identify a lead
- [ ] identify a few peer reviewers (at least 1-2 others)
- [ ] let ACM know
- [ ] put together a tenative timeline 
- [ ] draft the call for proposals 
- [ ] finalize the CFP
- [ ] create a plan of where to share the CFP
- [ ] review submissions
- [ ] reviewers meet to discuss? 
- [ ] work with ACM to put together issue
- [ ] do we need an engagement plan for when the special issue comes out? 

### Resources

- [link to project plan](https://docs.google.com/document/d/19yrYGEoTJ_1Z4obUOlfo5YWIOrCW2NkLrKb8Mo01mVw/edit?usp=sharing)
- See attached pdf that the editor-in-chief shared 

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

### Updates

5/24/21 
Created issue, updated project doc. Will discuss with Rich on 5/25/21

**Comment by eleventh19** [comment]
Met with the Editor in Chief (EIC) today. I think this makes sense to spend time, going to present at the next ops meeting and will review documentation

**Comment by eleventh19** [comment]
We let the EIC know that we'll follow up in August and start planning the call for papers and reaching out to potential editors/reviewers

**Comment by eleventh19** [comment]
Circling back on this and updating the project plan. Need to figure out a list of potential editors and to start drafting the call for papers. Once those are done, follow up with the EIC. Need to message them by the end of the month regardless

**Comment by eleventh19** [comment]
I need to email Leigh ASAP to update her. @LorrettaEGS is helping with getting this project back on track

**Comment by LorrettaEGS** [comment]
Thanks @eleventh19, I updated the document and it now reflects what the Call for Papers should include.

**Comment by eleventh19** [comment]
I added a [new doc](https://docs.google.com/document/d/1s5oIDOB6b0KI9750Kansfh3HNsnzOYDsBSh0yFjtc2Q/edit#) to just house the CFP draft, added some focus and potential guests. @RichatSCRF @cipherix @LorrettaGS let me know if you have any feedback

**Comment by LorrettaGS** [comment]
Hi @eleventh19, I added some thoughts to the document and made some adjustments to the content. Thanks for sharing the updated version.

**Comment by eleventh19** [comment]
Thanks @LorrettaGS! Made some updates to the doc after chatting with @ghettodev. Will get feedback from @cipherix asynchronously or during a meeting on Fri

**Comment by eleventh19** [comment]
we're going to more specifically focus on MEV. I will draft the overall write up on it. @cipherix please suggest some reviewers

**Comment by eleventh19** [comment]
I need to schedule a meeting with Leigh

**Comment by LorrettaGS** [comment]
Flagging for @eleventh19 that Leigh responded with her availability for a potential meeting. I can be available to join if needed on Friday, October 15th.

**Comment by eleventh19** [comment]
emailed Leigh an update and exploring some slightly different options

**Comment by eleventh19** [comment]
Struggling to find someone willing to review the papers, need to circle back with Leigh on the best way to proceed

**Comment by eleventh19** [comment]
Still struggling to find reviewers and haven't been spending as much time on this. I need to see if we can link this to any of the other projects / folks we're talking to
