### ISSUE TITLE
Place all public facing documents into the Docs Repo

### ISSUE THREAD

**Issue by ghettodev** [smartcontractresearchforum/research_team#114]
https://docs.google.com/document/d/1WSKokXrzjcwAXd38EWdx2CU7S0bYQV0xdjseQmM8bcg/edit#

Provide an explanation here and outline the steps.

Keep track of the docs in motion. 

Update the ticket as you complete work. 

Mention @ghettodev when docs need signoff.

Link to this issue when submitting PRs

**Comment by encore9870** [comment]
This is a discovery project now. Closing so we track all of them there.
