### ISSUE TITLE
Impact Awards: Public facing materials

### ISSUE THREAD

**Issue by ghettodev** [smartcontractresearchforum/research_team#118]
We need to make:

- [x] forum thread about the awards
- [x] github page for past winners, awards in general
- [ ] determine the social strategy for monthly awards

**Comment by eleventh19** [comment]
@jamesmcgirk can you please help review the language for the [forum post](https://docs.google.com/document/d/11VFQYhtPhFdebX-S-hOhU9QiAajpSoQJv8aVbcNzpLw/edit)

**Comment by jamesmcgirk** [comment]
Sure. Reverted some of my older edits. Happy to take another look after.

**Comment by eleventh19** [comment]
After being discussed in the ops meeting, the forum post copy and the [github draft](https://docs.google.com/document/d/18fpR52-EpI-84EuiZjc_RPQRKDNbGKXcUefIEtH72cg/edit#) were updated

**Comment by ghettodev** [comment]
First iteration posted to docs: https://github.com/smartcontractresearchforum/docs/blob/main/en/grants_impact_award.md

**Comment by eleventh19** [comment]
second impact award to be issued soon, updates made on forum appropriately. next step is to refine a monthly cadence/process

**Comment by eleventh19** [comment]
We let the awardee know and they confirmed. Will be posting to the forum soon. Going to shoot for issuing one every other month and updating the process appropriately. Will close out this card once we update the plan

**Comment by eleventh19** [comment]
Social media post is going out on Monday 9/6 at 10a PST and we will share with the guest and their communications colleagues

**Comment by eleventh19** [comment]
we also need to update the process for the impact award

**Comment by encore9870** [comment]
I would update the process for the IA, and will connect with Lucas to see how things can work.

**Comment by encore9870** [comment]
Lucas has been busy and not available to talk. We'll see if there are other ways of picking the award winner under our current human resource capabilities. If that is possible, we will build the new process around that.

**Comment by eleventh19** [comment]
We are going to circle back on this in the context of primary author outreach (#206) and our podcast.

**Comment by encore9870** [comment]
This is now owned by content and tracked in smartcontractresearchforum/core-projects#66 (iceboxed until we find the person to run it)
