### ISSUE TITLE
Impact Award #1 Engagement Strategy

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#119]
- Specific social copy for the first impact award
- Any other information to be shared / other venues to share on?
- Create a logo
- Doc done by mid-week
- Socials the following week

**Comment by eleventh19** [comment]
Next steps from outreach team:
1) finalize the [github language](https://docs.google.com/document/d/18fpR52-EpI-84EuiZjc_RPQRKDNbGKXcUefIEtH72cg/edit#heading=h.1bn0r965c7th)
2) finalize the [forum post language](https://docs.google.com/document/d/11VFQYhtPhFdebX-S-hOhU9QiAajpSoQJv8aVbcNzpLw/edit)

**Comment by eleventh19** [comment]
The first one took place and second one is under way. Next steps are to review the process and get the next one out

**Comment by encore9870** [comment]
This should be good reference after relaunching smartcontractresearchforum/core-projects#66
