### ISSUE TITLE
Project: Develop New Content Type: "X and the Blockchain"

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#120]
## Description
An occasional informal Survey of Knowledge (SoK) of blockchain-related research being conducted in an 'unusual' discipline such as anthropology, sociology, art, digital humanities, or communications. 

## Value to SCRF
*Content*: generates a series of articles which require less research than a typical summary.
*Engagement*: unexpected combinations of blockchain technologies and other academic disciplines will inspire spicy conversation and introspection. 
*Outreach*: Conducting interviews with experts can generate leads.
*Discovery*: SEO-friendly content, user-friendly and unexpected combinations of disciplines (e.g. Cooking and the Blockchain) may spark outside interest.

## Process
- [x] Generate example (Anthropologists and the Blockchain)
- [x] Share with Content Team and Ops
- [x] Create presentation
- [ ] Decide as a group whether we need this or not.

**Comment by ghettodev** [comment]
Can you add the template to this ticket and some details about what this task is about?

**Comment by jamesmcgirk** [comment]
Refer to [the following ticket](https://github.com/smartcontractresearchforum/research_content/issues/139)

**Comment by jamesmcgirk** [comment]
@jamesmcgirk finish project plan for presentation on Friday 7/23

**Comment by jamesmcgirk** [comment]
Deleted bc it was the wrong link.

**Comment by jamesmcgirk** [comment]
Presentation updated according to comments made during the presentation - [updated doc](https://docs.google.com/presentation/d/1kmMX6_CgBchxtY4QTxzxDdmqQO9dj7hWZv7esBJ766w/edit#)

**Comment by encore9870** [comment]
Interesting idea and glad it did take off and [get published](https://www.smartcontractresearch.org/t/mini-post-sociology-and-the-blockchain/585). It's an open content type in our Github for people to propose.
