### ISSUE TITLE
Project: Research on NFT Badges for Educational Certifications 

### ISSUE THREAD

**Issue by ishgun178** [smartcontractresearchforum/research_team#121]
### Project Description

Gather resources such as current projects that offer NFT based educational certifications. Use this information as reference to plan out SCRF's NFT based Badging System. 

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] Find and compile information about these projects that are publicly available on the web
- [ ] Dive deeper into specific hackathons and DAOs to find more implementations of NFTs in badging for educational purposes.

### Resources

- [link to project doc](https://docs.google.com/document/d/1N-9hzzoEQXH-i0kRzlcP2WQC9hibBnaUJhFi1BNh9dI/edit#)

**Comment by encore9870** [comment]
Good reference for smartcontractresearchforum/core-projects#85 or smartcontractresearchforum/core-projects#35. Closing now for maintenance and will continue the discussion once we launch one of the projects above.
