### ISSUE TITLE
Project: Onboarding document set for new hires

### ISSUE THREAD

**Issue by ishgun178** [smartcontractresearchforum/research_team#127]
### Project Description

It is important for any organization to have a standardized way of smooth onboarding for new hires. A detailed packet entailing all necessary information for onboarding would be a great way to begin this process. 

### Work Plan

- [x] Create an initial onboarding document to facilitate new hires navigate through docs referenced during meetings. This would include links and descriptions to all essential and most commonly referenced documents at SCRF, divided according to teams. 
- [x] Create SCRF's official onboarding handbook including everything from a welcome message and employee rights and responsibilities to SCRF teams, roles, and descriptions. 

### Resources

- [Initial Onboard Doc (Google Doc Links)](https://docs.google.com/document/d/1IAzayg9tJ_kj_nR1WTjyCpjc3EcJW0CjqMnSqRTyY44/edit)
- [SCRF Onboarding Handbook](https://docs.google.com/document/d/1clsoB92G6xkunXRL1k2ERdveGHOqRGWKDUvXcfWAzt8/edit)

**Comment by encore9870** [comment]
This is now tracked by the onboarding team&ticket smartcontractresearchforum/core-projects#29.
