### ISSUE TITLE
Project: A spreadsheet of well known blockchain podcasts for potential partnerships and for reference

### ISSUE THREAD

**Issue by ishgun178** [smartcontractresearchforum/research_team#129]
### Project Description

The aim here is to create a spreadsheet of active, well known podcasts with the goal of potential partnerships and for us to reference for our own podcast series. This list would be based on criteria such as potential overlap with SCRF's content, non biased discussions, features researchers, or highlights research reports. 

### Work Plan

- [x] Do intensive research (by potentially hearing a couple minutes of an episode or two from each podcast series) and create a list of 15 podcasts that match our criteria.
- [x] Add information such as recently covered topics, potential issues with the series, description of the podcast, and links to sample episodes for each selected podcast.

### Resources

- [lFiltered Podcast List](https://docs.google.com/spreadsheets/d/1DiWCpG8oTJVZdYa5adqv7xaMtKAynWrZJi42GucXaR4/edit#gid=0)

**Comment by encore9870** [comment]
Closing since the internship has been completed and this is no longer relevant.
