### ISSUE TITLE
Create Group Email Addresses

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/research_team#136]
**Description**
Identify group accessible email addresses for various onboarding and outreach tasks. This will prevent blocking.

**Comment by zubepaul** [comment]
Identified "billing" as a potential email to be created.

**Comment by ghettodev** [comment]
work@, grants@, invoice@, @info now exist. Do we need more?

**Comment by ghettodev** [comment]
@zubepaul says no. Closing.
