### ISSUE TITLE
Project: Smart Contract Summit

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#137]
We have been invited to create a research track as part of the Smart Contract Summit, where we will focus on governance, zk/privacy, and identity/reputation

**Comment by eleventh19** [comment]
This is the [updated plan](https://docs.google.com/document/d/1b_VcX1BNG3TnhHd4SB_KB-8cJFWMRyhHfP5-CCdZWaY/edit#). The Identity and Reputation panel is set and being pre-recorded 7/20. For the 2 governance panels, we have most of the speakers confirmed (need one more with experience transitioning to DAOs). Still ironing out specifics for the privacy/SNARKS panel and for any potential MEV presentation

**Comment by eleventh19** [comment]
Added room where the forum post and other pre-summit work (socials, chat posts) can be drafted to the [overall project plan](https://docs.google.com/document/d/1b_VcX1BNG3TnhHd4SB_KB-8cJFWMRyhHfP5-CCdZWaY/edit#)

**Comment by eleventh19** [comment]
Speakers have been set for the governance panels and all panelists have been sent the panel specific doc that includes a doodle for scheduling

**Comment by eleventh19** [comment]
The identity and reputation panel is set and the privacy and SNARKS panel is getting scheduled, as are the two governance panels

**Comment by jamesmcgirk** [comment]
I'll be doing the first draft of the governance thread for the forum, delivering it 7/23

**Comment by jamesmcgirk** [comment]
Working on adding AG bio to Z & P, place holder bios to CBDC in case others don't come in time.

**Comment by jamesmcgirk** [comment]
Completed first editing pass of [Identity and Reputation](https://docs.google.com/document/d/1lfxrGkDqeL45O36zakxrQyUv7Rsj1xU5f5ovSDV0X1M/edit) paper.

**Comment by eleventh19** [comment]
At this point, we have to finish doing the transcripts and show notes

**Comment by eleventh19** [comment]
One transcript done and others in process. One summary done, one in process, trying to get others done

**Comment by jamesmcgirk** [comment]
Edited one summary. @eleventh19 happy to do more if you need support.

**Comment by eleventh19** [comment]
Thanks @jamesmcgirk, will send them your way

**Comment by jamesmcgirk** [comment]
Working on Engagement efforts re: Summit threads while editing transcripts. CBDC transcript should be done today,estimate Friday or early next week for the next one (these are taking me about 5 hours per).

[Working doc](https://docs.google.com/document/d/14eyHUZ4G5X6rAuePJczN8Id8kFAe-bsf1dC6E9F241M/edit#)

**Comment by jamesmcgirk** [comment]
Finished polish of [CBDC transcript](https://docs.google.com/document/d/1IKguhPDBapEAtAeTC83OgcVBqqRtCxNo/edit) - starting SNARKS panel

**Comment by eleventh19** [comment]
I need to review the CBDC transcript, get in HackMD, and create a PR. In terms of show notes, @loicdrbx is working on the CBDC one and Tejas is working on the gov theory. Both should be up next week

**Comment by jamesmcgirk** [comment]
Here's the [SNARKs transcript]( https://docs.google.com/document/d/1Tgu1Dxm1lrG9N00stfMSAzXCpv1vBCmn/edit)

**Comment by jamesmcgirk** [comment]
Arranged a panel with LW, Jerry, Bill for SNARKS thread

**Comment by eleventh19** [comment]
finally added the last transcript, going to close out this out
