### ISSUE TITLE
Project: Generate one or two beginner-friendly threads

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#138]
Larry and I noticed that a few people have been intimidated by the forum, a possible solution would be creating beginner-friendly threads. An example would be 'a collection of blockchain syllabi' it's easy for forum newcomers to contribute to. Other examples: longform news articles relating to crypto, etc.

**Comment by Coinproz** [comment]
There is also the possibility of combining media formats with short-form discussion posts accompanying recorded real-time discussions that allow questions to be posed in real-time in line with how a newcomer would approach a subject.

**Comment by jamesmcgirk** [comment]
Something like this might be another example: https://www.ieee-security.org/TC/SP2015/papers-archived/6949a104.pdf

**Comment by jamesmcgirk** [comment]
Here's the thread that I referred to https://www.smartcontractresearch.org/t/a-collection-of-blockchain-syllabi-and-course-material/537/6

**Comment by jamesmcgirk** [comment]
Rich - forums aren't a great place for gathering information.  it's better to treat an original post as a syllabi, and to use the comments for proposed suggestions and additions... For the syllabi thread please move the information provided into the original post. (Eventually we'll create a HackMD out of it and a bounty). Check out how we do notable works for reference.

**Comment by jamesmcgirk** [comment]
@jamesmcgirk moved to approved status, build out the ticket

**Comment by jamesmcgirk** [comment]
@jamesmcgirk please move the syllabi suggestions into the parent thread. (Eventually this will be a Github file)

**Comment by jamesmcgirk** [comment]
moved.

**Comment by thedefisage** [comment]
Hi, 
looking to contribute to this, I can create learning resources for new members such as blockchain syllabi, and threads on blockchain terminology. Would that be helpful?

**Comment by jamesmcgirk** [comment]
@thedefisage a great way to start would be contributing to the following thread: https://www.smartcontractresearch.org/t/a-collection-of-blockchain-syllabi-and-course-material/537/6 - I'd love to hear what you think in the comments there and would be curious to see your additions

**Comment by jamesmcgirk** [comment]
Moved this back to proposed bc of initial pushback from ops and it's unclear if it would fit with our existing material

**Comment by encore9870** [comment]
I'm closing this issues that are not actively being worked on. Reach out to me if you have questions!
