### ISSUE TITLE
Pre-Summit Engagement Strategy

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/research_team#141]
**Description**
This ticket will track the engagement strategy for the summit. 
- [x] Create social media strategy
- [x] Forum post creation and promotion

**Comment by zubepaul** [comment]
Create 1 social per SCRF panel. That makes for 4-5 total socials.

**Comment by zubepaul** [comment]
Threads for each panel need to exist before socials go out.

**Comment by jamesmcgirk** [comment]
this one is probably done? moving to complete

**Comment by encore9870** [comment]
closing since it's completed
