### ISSUE TITLE
Program: Weekly Forum Maintenance

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#142]
## Description

The website needs to be monitored, threads tidied, information collated, etc.

**Comment by jamesmcgirk** [comment]
@ghettodev would it be possible to get edit access for other people's posts on the forum? If it is, I can start maintaining

**Comment by jamesmcgirk** [comment]
Should we create a project plan? MIght be good to have a weekly check list of items to review...

**Comment by eleventh19** [comment]
I think it would be good to have a plan that can outline how we will gather the info, where to store it, and how it gets shared. We can figure out who will do the work at least to get us started with this once the plan is in place

**Comment by jamesmcgirk** [comment]
I'll take a stab at making a project plan and update the ticket... @jamesmcgirk

**Comment by jamesmcgirk** [comment]
Rich says to open a Google doc and start cataloging issues, [we can use this one](https://docs.google.com/document/d/1L0gqEV3EnyYu4tJELOkVsfA5SEHdEGPb4TeMObLdrRg/edit#)

**Comment by ghettodev** [comment]
> @ghettodev would it be possible to get edit access for other people's posts on the forum? If it is, I can start maintaining

I think it would depend on who's posts you are editing and why.

**Comment by jamesmcgirk** [comment]
Beginning a missing tag hunt. Putting suggested tags in the doc above.

**Comment by jamesmcgirk** [comment]
@zubepaul we still need to meet for this updated project - maybe Monday?

**Comment by jamesmcgirk** [comment]
Tag updates completed, next agenda item: rollups, particularly w/r/t notable works suggestions. Issue: need to find experts to vet them

**Comment by jamesmcgirk** [comment]
##Update Meeting November 11, 2021
_Needs:_
- Ralph and James need to be able to add tags

_Glossary and Post Idea_
##Top Priorities 
1. Tags 
- Update recent summaries with new tags
- Retrieve the tags from the Github card
- Community-led discussion about maintaining and deleting tags
2. Information Architecture
3. Consistency
- Making sure each Category has all the necessary pinned posts 
- Subcategories? 
4. Freshness and Coverage
- Alerting the content team to gaps in coverage
5. Clean-up for Post Ideas and Glossary
- Every post idea should have a response and a decision
- Glossary needs to have an outcome and a decision
- Funnel them into the researcher application
6. Directing people to Discord/research applications/managing Impact Awards
- top line link

**Comment by encore9870** [comment]
This is now longer relevant. smartcontractresearchforum/core-projects#31
