### ISSUE TITLE
Discord is missing Grants & Bounties Feed

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#144]

**Comment by Coinproz** [comment]
We talked about this today actually, and for the sake of not over-segmenting communications channels it makes sense to hold off until there is more chatter in the main before starting a new channel

**Comment by jamesmcgirk** [comment]
Makes sense!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Coinproz** [comment]
I am going to introduce the micro-grant recipient to the general chat next week, but there is the possibility that segmenting grant recipients into a communication channel pre-emptively may have net negative results.
