### ISSUE TITLE
Project: Update Boilerplate with new language

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#145]
Description:

Once the new copy generated by the branding exercise is incorporated, the marketing boilerplate document should be updated with the new wording and concepts.

**Comment by jamesmcgirk** [comment]
[Boilerplate](https://docs.google.com/document/d/1reyFhD-ncRtp4F5zhkjJIRjTdAWTrtodR0yEe1q7q7M/edit#heading=h.oooeapyb8e28)

**Comment by eleventh19** [comment]
We have someone joining to help with updating the boilerplate and linking that to a landing page build (need to add a card for that)

**Comment by eleventh19** [comment]
I need to add Maria here and ask her to write about updates here.

**Comment by jamesmcgirk** [comment]
should this issue be integrated with #155 ? Once the boilerplate is updated, I can work with Maria on #3 (press kits)
