### ISSUE TITLE
Create an Onboarding / Hiring Log

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#146]
## Description

Create an onboarding/hiring log as first attempt to keep track of onboarding and hiring. Began with Aug 3rd entries, will add previous entries from this month.

## Workflow 

- [x] Create document
- [x] Present to Onboarding group
- [x] Incorporate changes

**Comment by jamesmcgirk** [comment]
[Log](https://docs.google.com/document/d/1XbKucwFlZ4AeiTYY0bMhNMNaOlTIMbNKQA1rqUb0BbI/edit)

**Comment by eleventh19** [comment]
Thanks James. I just filled out my most recent convos and I'll make sure to start using this for all hiring and/or onboarding related discussions

**Comment by jamesmcgirk** [comment]
Going to move this into in-progress since we're using it...

**Comment by eleventh19** [comment]
Created a log and were actively using it. Might need to consider moving older convos into a single archive doc to male the doc load times faster. 

Other onboarding docs are being updated such as the tracking spreadsheet and checklist. @jamesmcgirk do you think we need to make any changes/do anything else with this or can we close this out?

**Comment by jamesmcgirk** [comment]
I think we can close it out. Moving to Complete.
