### ISSUE TITLE
Categorization project: Sociologists and the Blockchain

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#147]
## Description

Placeholder text for a project plan that will outline a plan to catalog the information about sociologists and the blockchain that we've assembled and potentially reach out to one or more of them as part of our podcast series.

## Work Flow
- [x] Connect with researchers
- [x] Define parameters, assay data
- [ ] Write up
- [ ] Presentation

**Comment by eleventh19** [comment]
let me know if I can help with creating the project plan

**Comment by jamesmcgirk** [comment]
@eleventh19 I'll take a stab at it, K had some thoughts which I'll incorporate

**Comment by jamesmcgirk** [comment]
[Project Plan](https://docs.google.com/document/d/1NZJezFfHyYO-PYwud5M1kJlmzkvia5n3Pa0kPhlVphM/edit#heading=h.3tjwxymr5e9k) @eleventh19 if you'd like a look

**Comment by jamesmcgirk** [comment]
Not seeing any more activity, going to write up a draft

**Comment by jamesmcgirk** [comment]
merging with #120
