### ISSUE TITLE
Project: Create Visualization of SCRF for External Audience

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/research_team#149]
**Description**
Create a visual representation of SCRF as an organization so that it is easier for brand new members and external audiences to understand all that is happening at SCRF and to help them orient to their current position in the organization. This will also help outline an aspirational trajectory for new members.

**Comment by encore9870** [comment]
This is overseen by Paul's onboarding team. Closing this so work is tracked in smartcontractresearchforum/core-projects#29 or the team's master board.
