### ISSUE TITLE
Project: Create Comment Incentivization Program

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/research_team#150]
**Description**
A transitional program that incentivizes quality comments from the community at large. 
- [x] Create proposal
- [x] Present to Ops
- [x] Impement round one
**Resources**
- [Project Overview](https://docs.google.com/document/d/1fCdczrUAmH5fzxHLNdnt7LhRVBgXsUkZ0oKhBaAdzas/edit#)

**Comment by zubepaul** [comment]
Providing edits and recommendations. Rachel preparing to make a pitch during the Wednesday call 9/1

**Comment by zubepaul** [comment]
@rjx223 getting added to this ticket

**Comment by zubepaul** [comment]
Additional edits made, @rjx223 ready to present to the Wednesday group for feedback

**Comment by rjx223** [comment]
@zubepaul @eleventh19 
Made some changes to the process of the initiative, please take a look and let me know your thoughts.

**Comment by zubepaul** [comment]
To be presented at Wednesday "all hands" call.

**Comment by zubepaul** [comment]
PR for repo documentation needs to be reviewed by @ghettodev 
Poll is now live on the forum 
https://www.smartcontractresearch.org/t/scrf-contributor-recognition-and-rewards-initiative/860

**Comment by zubepaul** [comment]
Edits made in Hackmd version of document. Most changes made, a few follow up questions in comments for @ghettodev 
https://hackmd.io/DY8G9Fo7RF-EAbyXiSaZrQ?both

**Comment by zubepaul** [comment]
Public-facing language under review by Maria. Edits to the forum post need to match these edits. I will coordinate with @rjx223 to get that completed.

**Comment by zubepaul** [comment]
Forum post edited by @rjx223 to conform to public-facing language.

**Comment by rjx223** [comment]
The document is ready for approval @ghettodev 
Thank you!

**Comment by eleventh19** [comment]
not ready for review yet, @rjx223 is revising based on template and then @marvino3 is going to review

**Comment by marvino3** [comment]
The gdoc was revised. Approved on my end @rjx223 and @zubepaul. Should be ready for hackmd and final approval.

**Comment by rjx223** [comment]
Working out the payment structure with @zubepaul 

Will update when that is finalized and reflected in HackMD

**Comment by rjx223** [comment]
Contributor R&R doc on Hack is ready for final approval @eleventh19 @ghettodev

**Comment by zubepaul** [comment]
Connect with @vsterling to get involved with this process as a PM.

**Comment by rjx223** [comment]
@LorrettaGS @zubepaul and I met to discuss the future of the initiative and what it could look like and how to evolve it into a community-driven mechanism. Some of the ideas proposed include:

- Creating identities/roles within the community for nominators, open to everyone
- Establishing a new channel on Discord for nominations to be made openly by community members
- Providing a micro-payment for peoples’ whose nominations become finalists
- Creating an abbreviated template for nominations in Discord that community members can follow; ie. link to comment, one-sentence summary for context, why nominated, etc.
- Discussing the initiative twice per month in community calls
- Initially to review past comment winners/current nominees
- Secondarily, subsequent to the publishing of a poll, where finalists would be invited to join and discuss their comments/thought processes in depth; this would take place in either Americas or APAC call, depending on the nominee's time zone
- Possible overlap of this initiative with SCRF Weekly Roll-up as an avenue to promote community engagement and nominations

https://hackmd.io/DY8G9Fo7RF-EAbyXiSaZrQ

**Comment by eleventh19** [comment]
@rjx223 is there anything else that needs to happen in terms of the initial launch of the program? if not, what do you think about closing this card and starting a new one that will focus on improving the process?

**Comment by rjx223** [comment]
That is fine by me. Thanks, Eugene.
