### ISSUE TITLE
Draft a SCRF + Governance Strategy

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#154]
The goal of this project is to create an initial strategy to review with the SCRF ops team. This strategy will focus on the mix of activities that SCRF could focus on to specifically support governance activities in the industry. A subsequent project will entail abstracting the revised version of this strategy to be a general SCRF+topic-area strategy.

**Comment by eleventh19** [comment]
This is the [first proposed draft](https://docs.google.com/document/d/11EGBwiZqEHrUnvfInfbGsL_7T_l8j00TMzfuwVJMR4o/edit?usp=sharing). I will update this and review with Rich to see if I'm on the right track before sharing with the wider time

**Comment by encore9870** [comment]
This is now rolled into a wider outreach & special projects discussion. I'll close this ticket since it's not being used for updating progress on this task.
