### ISSUE TITLE
Branding Updates

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#155]
This is the next phase of project #113. This entails:
 - [ ] Brand landscaping doc
    - [x] Update brand boilerplate language
    - [x] Validate brand messaging
    - [ ] Crystalize brand guide
    - [ ] Update twitter description based on brand language
    - [ ] Update linkedin description based on brand language
    - [ ] Update Git landing page
    - [ ] Create a forum landing page
    - [ ] Create welcome message for discord bot
    - [ ] Check in with onboarding and community teams to see if there is any other stock welcome language needed

Once the above are all completed, the next step will be starting a new project relating to getting a landing page for SCRF in place.

**Comment by eleventh19** [comment]
need to get Maria and Rachel linked to our git and then to tag them here

**Comment by eleventh19** [comment]
adding @rjx223 as she's supporting. will add Maria as wel

**Comment by eleventh19** [comment]
reviewing the Brand Guide, meeting on Monday to review

**Comment by eleventh19** [comment]
meeting pushed to 10/4 as we had to sort out the git doc template (project #173). will update the ticket after that meeting takes place

**Comment by eleventh19** [comment]
@marvinok3 please provide an update and outline next steps when you get a chance

**Comment by eleventh19** [comment]
[this project plan](https://docs.google.com/document/d/1vLSElaLxywMTp1gk0f7fT2oQhe4o0_3l7gBoWcQMm7c/edit#heading=h.h50zkyeuvm32) was created by @marvino3

**Comment by marvino3** [comment]
Sent out a [form](https://docs.google.com/forms/d/1NGVTHHC5BgFBz5mnOKgPr_KfNN-BUsEG44WgiZXRdWE/edit) to gather mission/ vision feedback and validate our messaging to support brand guide updates

**Comment by marvino3** [comment]
Waiting on a [form](https://docs.google.com/forms/d/e/1FAIpQLScWZ2wfBDR8XWlQvTv4KfThsELR_9mrSgW0IpnC9YSfcLzUug/viewform?usp=sf_link) response from @ghettodev. Then, analyzing and incorporating comments to update the boilerplate language over the following weeks

**Comment by eleventh19** [comment]
linking the [exercise outcomes](https://docs.google.com/document/d/1xRre3UOao5qx3umljls_fOJtrnDxflJyveOdydP14rY/edit#heading=h.orrfj3rovqjt) doc here to not lose track of it

**Comment by marvino3** [comment]
The [Mission/ Vision Messaging doc](https://docs.google.com/document/d/1xRre3UOao5qx3umljls_fOJtrnDxflJyveOdydP14rY/edit#) is updated - waiting on final approval from @ghettodev @eleventh19. Please see the last few pages for updated language.

**Comment by eleventh19** [comment]
@marvino3 what're the next milestones? Once the brand guide is fully updated?

**Comment by eleventh19** [comment]
I'm going to go ahead and close this out @marvino3. We now have a much more robust [discovery board](https://github.com/orgs/smartcontractresearchforum/projects/17/views/1) where all relevant projects for branding are being tracked
