### ISSUE TITLE
Decentralization Project Formation & Kickoff

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#157]
This is the project management tracking for the Decentralization project that we have been getting underway. The first steps were
* get a notable works list
* get input on the list
* put together a forum draft

This are in process/almost done. From here, we will have to focus on:
* getting a more formal project plan in place
* getting summaries done on some of the notable works 
* see who else wants to join

**Comment by eleventh19** [comment]
@cryptomarabout can you please link to your docs and the relevant content github cards when you get a chance?

**Comment by cryptomarabout** [comment]
Here are the links: 

- Notable Works: https://github.com/smartcontractresearchforum/research_content/issues/160
- Discussion Post: https://github.com/smartcontractresearchforum/research_content/issues/161
- Research Prospectus: https://docs.google.com/document/d/1rejxut7f-5ohCzrHx1FkHnRgcHeAMZSv/edit

**Comment by cryptomarabout** [comment]
Update: 

- [Notable Works](https://github.com/smartcontractresearchforum/research_content/issues/160): reviewed by cypherix, I will add to the list a suggested paper and the last one I found
- [Discussion Post](https://github.com/smartcontractresearchforum/research_content/issues/161): On standby while finishing the research prospectus
- [Research Prospectus](https://docs.google.com/document/d/1rejxut7f-5ohCzrHx1FkHnRgcHeAMZSv/edit): In progress with the help of Deane and Larry (definition of research methodology etc.)

**Comment by cryptomarabout** [comment]
Update:

- [Notable Works](https://github.com/smartcontractresearchforum/research_content/issues/160): 2 papers added, peer review finished, GTM questions finished, have to check GTM strategy with James and Paul.
- [Discussion Post](https://github.com/smartcontractresearchforum/research_content/issues/161): On standby while finishing the research prospectus
- [Research Prospectus](https://docs.google.com/document/d/1rejxut7f-5ohCzrHx1FkHnRgcHeAMZSv/edit): Still in right track with the help of Deane and Larry.

**Comment by cryptomarabout** [comment]
Update:

- [Notable Works: ](https://github.com/smartcontractresearchforum/research_content/issues/160) Published.
- [Discussion Post:](https://github.com/smartcontractresearchforum/research_content/issues/161) On standby while finishing the research prospectus
- [Research Prospectus:](https://docs.google.com/document/d/1rejxut7f-5ohCzrHx1FkHnRgcHeAMZSv/edit) Lacking few pages + bibliography before peer review

**Comment by Siemingfong** [comment]
Notable Works: Notable works: “Decentralization Measurements” research_content#160
Discussion Post: Discussion Post: “A Curated List of Threats to Decentralization” research_content#161
Research Prospectus: https://docs.google.com/document/d/1rejxut7f-5ohCzrHx1FkHnRgcHeAMZSv/edit

**Comment by cryptomarabout** [comment]
- [Notable Works:](https://github.com/smartcontractresearchforum/research_content/issues/160) Published but I will add new papers in few weeks to make it more complete
- [Discussion Post:](https://github.com/smartcontractresearchforum/research_content/issues/161) On standby while finishing the research prospectus
- [Research Prospectus:](https://docs.google.com/document/d/17hvUZu0G2exS9mhSZ0Y63SNi20Hf6fKjUzElXV7_3AY/edit?usp=sharing) Draft finished + peer review process started

**Comment by cryptomarabout** [comment]
Research prospectus finished and peer reviewed by Chris and Deane.
@jamesmcgirk can you please give it another review ? 
https://docs.google.com/document/d/1-NHeoAJn3cw2c_WhLVR87O3y0ZVOF_i5C2LEqfNi1C8/edit?usp=sharing

Thanks in advance

**Comment by jamesmcgirk** [comment]
@cryptomarabout checking it out now!

**Comment by cryptomarabout** [comment]
- [Notable Works:](https://github.com/smartcontractresearchforum/research_content/issues/160) Published but I will add new papers to make it more complete
- [Discussion Post:](https://github.com/smartcontractresearchforum/research_content/issues/161) On standby
- [Research Prospectus:](https://docs.google.com/document/d/1-NHeoAJn3cw2c_WhLVR87O3y0ZVOF_i5C2LEqfNi1C8/edit) Peer reviewed by Chris, Deane and James. Ready to be published somewhere (we still have to define how)
- [Project Plan:](https://docs.google.com/document/d/1LlG7XDW630vmrFMYvU_g5mvD8cwqve5DElAy-de7r9k/edit) TODO
- [Presentation support:](https://docs.google.com/presentation/d/1sPCYC21NAspTChEKb6lDs0wV5fAAph9pqBFQVS58oX0/edit) TODO

**Comment by cryptomarabout** [comment]
- [Notable Works:](https://github.com/smartcontractresearchforum/research_content/issues/160) Published. (Seeing the process for iterative improvements)
- [Discussion Post:](https://github.com/smartcontractresearchforum/research_content/issues/161) 1st version Finished. On standby
- [Research Prospectus:](https://docs.google.com/document/d/1-NHeoAJn3cw2c_WhLVR87O3y0ZVOF_i5C2LEqfNi1C8/edit) Finished. Ready to be published somewhere (we still have to define how)
- [Project Plan:](https://docs.google.com/document/d/1LlG7XDW630vmrFMYvU_g5mvD8cwqve5DElAy-de7r9k/edit) TODO
- [Presentation support:](https://docs.google.com/presentation/d/1sPCYC21NAspTChEKb6lDs0wV5fAAph9pqBFQVS58oX0/edit) Finished
- Video presentation to community: Done during 11/11/2021 community call (but not recorded entirely, may do it again)

**Comment by eleventh19** [comment]
@cryptomarabout anything else outstanding here? If not, let close this card out for now as we have reached the initial milestone and we can create a new card if/when we decide to explore further milestones

**Comment by eleventh19** [comment]
No other updates coming unless we decide to embark on a primary research project in this direction. Until that happens, this card is getting closed
