### ISSUE TITLE
Revisions to the community call

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#160]
Building off of #115 to review any potential changes needed to the community. The goal is to make the goals as engaging and beneficial to community members as possible so we want to play around with the structure to figure out the best way to do that. 

If you have any thoughts, please let me know. 

Next steps
- [x] Review the feedback so far
- [x] Propose an update to the call ASAP to the ops team
- [x] Put together some ideas 
- [x] Get feedback to the call in a community call 
- [x] See if more ideas are needed/need to be tried

**Comment by jamesmcgirk** [comment]
I'll begin using the new format this week and will report back with results... [Community Call notes](https://docs.google.com/document/d/1M1swcWCzwjEg9xGSH8yYgXoPXxff22GnMjpSw1qkP9U/edit#) from our meeting

**Comment by eleventh19** [comment]
Shifting the focus for today's call to hearing what people are working on, giving a chance to discuss what's on people's minds, going to mention the potential pod project, q&a, and go over SCRF mission and projects if there's time

**Comment by eleventh19** [comment]
coordinating with @jamesmcgirk to update the Africa/APAC/EU call structure in the next week, no more than two. also, @LorrettaEGS and Maria are giving feedback on how to update the community calls which are reflected in the [project plan doc](https://docs.google.com/document/d/18aGFdpn9GUr7TpCZsSj83ICMoXandk1HV-ZFWFBerVg/edit#).

**Comment by jamesmcgirk** [comment]
@eleventh19 can we close this?

**Comment by eleventh19** [comment]
let's close this once we feel comfortable recording those calls, see any other ideas for revision come up this week

**Comment by eleventh19** [comment]
we're going to start recording these the week of 9/27 and will close this card then

**Comment by eleventh19** [comment]
We started recording these. Need to develop a better process for sharing the videos. At this point, I'm going to close this card. Will work with @LorrettaGS and others to figure out an overall topic schedule for the calls, topics to cover vs presentations to go through/work to highlight, etc. We'll want to add a chance for anyone who goes through #167 to be able to present on their work to the community. Might make sense to do the same for #44. We are going to clean up the community related cards and get our general project planning organized around it
