### ISSUE TITLE
Project: Proposed SCRF Taiwan regulation discussion group

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#163]
## Description

Astrid has been discussing the following idea with Sean and Seth(?), she’s proposing setting up SCRF/Taiwan branch association. Has interest from professors, thinking of it as a platform for academic exchange and policy discussion.

**Comment by jamesmcgirk** [comment]
Maybe we could combine [the following issue](https://github.com/smartcontractresearchforum/research_team/issues/162)

**Comment by 29988122** [comment]
Could be run in parallel(separately), or together.

It all depends on what seth/sean/twan and other ppl's idea is. I feel like they're going to do something bigger, rather than my simple/dumbed down version. But that's just my guess. Will update the ticket status(merge or not) after the meeting.

**Comment by Siemingfong** [comment]
@29988122 Together is the best solution

**Comment by Astridchou** [comment]
We hope to build a platform for researchers in Taiwan which respects every researcher's idea and gathers everyone's power to promote every idea that is approved by SCRF. So maybe it is better to be together.

**Comment by 29988122** [comment]
Reached consensus with Seth, Astrid, and Collin.

Current progress: a proposal with:
- members
- org structure
- org activites (classes, panel talks, for example)
- cost estimations
- impact - how can its activities affect the univ, growing talents in the process(e.g., ask univ blockchain club members to have a research topic about certain industrial field, and make it a post on SCRF, lecture it in the events facing industrial ppl, etc.), while having a positive impact to the industry where the misconceptions towards blockchain is immense.(banking, insurance, accounting, law, etc.)

It's a WIP - James, me, Sean, Astrid, and other members who reached consensus about how the activities shall be - will be drafting the proposal together. The impact will be carefully examined to ensure it's inline with SCRF's branding policy and SCRF's mandate.

**Comment by Siemingfong** [comment]
It's our first draft version of the proposal
https://docs.google.com/document/d/10_1watcPCSCrcgxD4QPOyjwwldejZAHHR05qqGfPzto/edit?usp=sharing
