### ISSUE TITLE
Create Discord Explainier Documentation

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/research_team#168]
**Description**
Create documentation for how discord is used as well as roles and bots. Will be useful for community leads. 

- [ ] Identify bot functions
- Welcome message for onboarding
- Meeting announcements
- Quizzes and unlocks
- 
- [ ] Identify roles for chat
- Community Member
- Community Lead
- Contributing Member
- Project/Team Lead
- Researcher
- Researcher Lead
- Ops
- [ ] Calendar and events
- [ ] Identify channel needs
- [ ] Articulate culture here

**Resources**
Onboarding Document: [Automatic Message](https://docs.google.com/document/d/1J53ID6E23-WYKr0q0r-Pt5qlU6_fiHG3syI-0hwAr0c/edit#heading=h.mhao50ln3bb)

**Comment by zubepaul** [comment]
Updated ticket to capture more of the to-do list on this small project.

**Comment by zubepaul** [comment]
Explore automation of information gathering through discord and discourse

**Comment by zubepaul** [comment]
Adding @LorrettaGS so she can also brainstorm onboarding and automation needs

**Comment by eleventh19** [comment]
@nakedwinnie, will be asking for your help on this one. please coordinate with @LorrettaGS and @zubepaul and see #153

**Comment by encore9870** [comment]
I believe this is now a part of the wider onboarding discussion. Closing this for now.
