### ISSUE TITLE
University Blockchain Club Engagement

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#169]
[Google Drive Folder](https://drive.google.com/drive/folders/1Uu9uc3xR_2h1872GN289kwOpDSbO5aHo?usp=sharing) 

The goal of this project is twofold: 
1) create an outreach strategy for blockchain club engagement, and 
2) start outreach to create a pilot of engagement in the Fall of 2021. 

As part of 1), we need to figure out how we specifically want to engage with clubs. What are the specific 'offering' we are providing them - inter-club reading group (by region or globally), pathways to advance as researchers, structuring events that bring together researchers/practitioners and students, etc. 

Once we have our sense of a menu of options of how we can engage with clubs, then we have to reach out to a few clubs. We currently have a few connections with CMU, Penn, U Minnesota in the States and NTU in Taiwan. 

[Project plan](https://docs.google.com/document/d/1ipmdlvdOrti1admo1bwC3CboMVFJozTBmdrROZArLuM/edit#heading=h.ig1sweegfy7n) that @ishgun178 put together over the summer. @Ashley-Y-Lin is going to be helping with this going forward and I'm interviewing some interns from different uni's in North America and speaking to one person in Singapore as well as coordinating with the Taiwan team

**Comment by eleventh19** [comment]
Here is a [new project plan](https://docs.google.com/document/d/13ATuQut-y3x7-MNh23c5jjHfEFgyAzO2OoYuYLm33bY/edit) being worked on by @Ashley-Y-Lin and @twan-dev

**Comment by eleventh19** [comment]
Met with @Ashley-Y-Lin and @twan-dev to discuss. Will regroup asynch by the end of the week to review specific event ideas. Interviewing a potential intern to support as well. We will review with @ghettodev next week

**Comment by eleventh19** [comment]
Adding @Newmsie10 as well (welcome!). @Ashley-Y-Lin and @twan-dev, he won't be able to make it to the meeting on Monday so if I miss any background info ahead of the meeting, please add it here. 

Basically, we have [this](https://docs.google.com/document/d/19d57PRgwghcA1HBvdyJbRY5dZOAHvLi-8fH_QAkpZRs/edit#) ideas doc where we have been hashing out the ideas that we are going to present to some clubs. The first two clubs we'll reach out to with these ideas will be Penn and CMU. given our connections there. We don't necessarily have to have the same pitch for both uni's and can/might end up adjusting once we chat with them. From there, we'll want to pitch the refined idea list to a few more clubs. The goal is for all of this to take place this Fall so we can be ready for the start of the Spring semester.

**Comment by eleventh19** [comment]
Found [this new CoinDesk ranking](https://www.coindesk.com/learn/2021/10/04/the-top-universities-for-blockchain-by-coindesk-2021/) of blockchain uni's

**Comment by Newmsie10** [comment]
Twan and I created a list of possible options for engagement opportunities for clubs [here](https://docs.google.com/document/d/19d57PRgwghcA1HBvdyJbRY5dZOAHvLi-8fH_QAkpZRs/edit#heading=h.fbepbtittkat). I think the main concern will be how we can deal with students/clubs who are trying to do more hands on project based work rather than group readings

**Comment by encore9870** [comment]
- TL;DR for progress up to Oct 14 is in this [slide](https://docs.google.com/presentation/d/1F9iE3HH8j96f9pwZCo2umLeBVObURQTkByvVTCZDlWI/edit?usp=sharing)
- Just met with Ishgan an hour ago, and he's going to let us know when CMU's next brainstorming club session is
- @Newmsie10 and I will write up a document to send&pitch to other clubs on the list

**Comment by eleventh19** [comment]
Ishgun followed up to let us know that someone from the club will follow up in the next week to set up something up the week of 11/8 (hopefully 11/9). Meeting with someone from RMIT soon. Caught up with @Newmsie10 and will chat with @twan-dev tomorrow

The goal for now is to a) iron our the 'menu of options' of the kinds of things we can help clubs with and b) run that by a few more clubs so we can get their feedback. 

Things to consider for now (we don't have to go with this but just ideas that come to mind based on discussions so far):
- Reading group
- Panel discussion 
- Presentation on a specific topic
- Research focused meetup
- Brainstorming (project or research; from a technical or PM perspective)
- whatever the research equivalent of a hackathon is

**Comment by encore9870** [comment]
Eugene's meeting with RMIT went really well, they are excited about having so many options to choose from, and will follow up once they have internally leaned towards one of the options. 
Meanwhile, @Newmsie10 while waiting for responses, we can and should make time to connect and pitch to other universities on the list

**Comment by Newmsie10** [comment]
Just ran a few ideas past the UMN Blockchain Club and they are actually working on a technical project for this semester and already had their format set and are not very interested at the moment. They said they would be open for ideas for the next 2022 spring semester and are enthusiastic about how SCRF can give them some content that they may have been lacking from before.

**Comment by encore9870** [comment]
Current state:
We've decided that instead of proposing ideas to clubs, we would just talk to them directly, and see how SCRF can provide the most value.
Eugene is reaching out to existing connections and we'll move to next steps once we've heard from them.

**Comment by eleventh19** [comment]
CMU event is happening on 11/16. I just pinged the UT Austin club president. We recently got connected to the Cornell folks, going to follow up with them. Need to ping regarding the UPenn club and RMIT club

**Comment by eleventh19** [comment]
meeting the club president from UT Austin tomorrow, emailed about Penn yest, and will follow up on Cornell right now

**Comment by eleventh19** [comment]
setting up a brainstorming session with the UT Austin club on 12/5 at 4p

**Comment by eleventh19** [comment]
this is generally going to be a subset of the #208 outreach mandate and an on-going outreach activity

**Comment by eleventh19** [comment]
I am going to close this out as this is not being treated as a project separate from ongoing outreach, specifically university outreach
