### ISSUE TITLE
Onboarding Group Calls

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#170]
- APAC Time call
- Europe Time call
- Americans Time call

**Comment by jamesmcgirk** [comment]
To be discussed during our moderation meeting call 9/13. Suggest starting with two, one for US/Euro zone, one for APAC

**Comment by jamesmcgirk** [comment]
Discussed during the moderation call... idea is to have two calls (potentially three) - basic outline introductions, basic presentation, answering questions, discussing projects in motion

Scheduling - mimic community calls or experiment with timing?

**Comment by jamesmcgirk** [comment]
First one scheduled for next week, going to develop some materials for it (essentially adding Tania's proposed slides to the existing doc)

**Comment by eleventh19** [comment]
we are having some calls internally this week, discussing the next steps on Fri, and planning a recurring internal onboarding call starting next week (starting 10/11). we are looking to start a call that will take place at least once on a bi-weekly basis the following week. @ttaloute @LorrettaGS

**Comment by LorrettaGS** [comment]
For clarity the bi-weekly call will occur before the Thursday Community Call right? That would be an opportunity for people to come ask questions related to onboarding, ensure that they have filled out all the necessary paperwork and what not. Have we determined internally who might fill that bi-weekly role? @eleventh19 @jamesmcgirk @ttaloute

**Comment by eleventh19** [comment]
We should plan when we want we want to do the first public one

**Comment by eleventh19** [comment]
@vincenzospaghetti there's an onboarding call coming up right? Once these are regularly scheduled, can you please close out this card? Thanks!

**Comment by vincenzospaghetti** [comment]
@eleventh19 This is scheduled and done. Will be every first Monday of the month. 2 PM EST time. It can be found on the calendar in Discord. Also will be posted on general calendar when we work that out.

**Comment by encore9870** [comment]
Closing since it's completed. Good work!
