### ISSUE TITLE
'Scope of work' docs for our initial proposed primary research grants

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#171]
Working on a scope of work documents for the first three proposed research support grants. We are currently talking to three researchers about supporting their projects. I'm currently working on creating a scope of work doc for each researcher and a template based on these three for future use. This task will be closed when the three documents are shared with the relevant researchers and the general template is created

**Comment by eleventh19** [comment]
@ghettodev I made [a template](https://docs.google.com/document/d/1uK-_7EltNZmk6Mqkj8lA6ZqHQ-Q1IGfTEBhEabAFrUY/edit#) to use overall. Also started an outline of [a process](https://docs.google.com/document/d/1tEEtSPpMOn8aA2kPnmSeIav542Rk8dQlDlhzBcYrCqU/edit) for the future. Will need to make a form to capture some of the info to fill out the template. 

Overall update, we have 2/3 docs finalized with the first set of researchers we're working with. This card will be closed when the third doc is finalized and then there will be a new card added to cover the project of getting a process for this worked out/improved

**Comment by ghettodev** [comment]
Convert this to an epic that reflects the entire PI Grants project pls.

**Comment by eleventh19** [comment]
add disbursement schedule to the milestone schedule, with approximate timing. I also want to create an application for this to run by the ops team

**Comment by eleventh19** [comment]
still need to update the general template for this. might end up tapping @vsterling @LorrettaGS @twan-dev to help at some point next week. 2/3 initial projects to support have been formally started, wrapping up the final one

**Comment by eleventh19** [comment]
need to follow up with @vsterling @LorrettaGS @twan-dev during the next PM meeting

**Comment by eleventh19** [comment]
this has gotten slightly delayed given realities of resourcing and priorities. next steps are creating a draft application, thinking through who would review applications, draft an expectations doc, and review the steps to see what's missing. if possible, will shoot to get some progress before 12/20 on those docs

**Comment by eleventh19** [comment]
going to be bringing this up with the PMs team to have some kind of mechanism to receive applications in place by ETH Denver

**Comment by vsterling** [comment]
Currently building off of what Eugene had to outline a full process from application to review to acceptance. Next is to write this draft document and soon publish on github. I also created a draft [application](https://docs.google.com/forms/d/1n1AVbvpZSfbmOVGJeQc13OyI7ZDOD0tUkvhc6NaN0hU/edit?usp=sharing) on Google forms.

**Comment by eleventh19** [comment]
We have a few potential grant applicants to review next week and based on that conversation, will review the process we want to have in place for people who want to apply to get small research grants at SCRF

**Comment by eleventh19** [comment]
the next step will be to create an overview of what a grant request forum post could look like. then review by core ops, and upload to the forum, then close this card

**Comment by eleventh19** [comment]
Created documentation for a [forum post](https://docs.google.com/document/d/1q9f4SVjr84lChqxzIoX69JP4tF5Yvh23S6VEEzGwbyQ/edit) and a [github post](https://docs.google.com/document/d/12UZ10e_NBWY9jmXu9-6G6BAnkfKCkH-m0ESGiNwMkuU/edit#heading=h.j6ezukkrgqa8). These will both need to get updated as we improve the process but the initial milestone this card should get us through is having a clear process where someone can apply and get evaluated for a grant. Right now this is entirely ad hoc

**Comment by eleventh19** [comment]
Actually, I realize I'm going to close this out as we have this [template](https://docs.google.com/document/d/1uK-_7EltNZmk6Mqkj8lA6ZqHQ-Q1IGfTEBhEabAFrUY/edit#) for the scope of work, so the goal outlined here was achieved. smartcontractresearchforum/operations#34 is the issue that captures the wider project around research support grants

**Comment by eleventh19** [comment]
This issue is closed as the scope of work template is created
