### ISSUE TITLE
Documentation Revision

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#173]
This is to manage the revision of github documentation. This entails:
- [x]  general git content creation guide
- [x] documentation process outlined
- [x]  document status audit
- [x]  hackmd tags updated
- [ ]  create content type specific templates
- [ ]  review and update each doc
- [ ]  update git landing page
- [ ]  update ToC
- [ ]  update process for creating new docs/ updating old docs
- [ ]  ensure all docs are live (listed or unlisted) in git

Current draft of the [github template](https://docs.google.com/document/d/1AsU3r7v1S1r6I3IFXG6l0VLlePnWVyRLFOkgWxlmrSU/edit#)

**Comment by eleventh19** [comment]
Tagging @marvino3 and @Rjx223 here as well

**Comment by marvino3** [comment]
Attached is a copy of the [two sample git pages](https://docs.google.com/document/d/15EVG2e5DjHXvaXXY_H48I8ENDBsKVSeCZJddp2OLMxw/edit).

1) The first is the SCRF Weekly Community Calls document, which we already worked on in the Git Template doc, but I wanted to ensure we were happy with the final result. 
2) The second updated document is our Style Guide. I think this document is a crucial part of our brand guide and git updates. Therefore, using this as the second piece would kill two birds with one stone. I updated the header, footer, and restructured the body for clarity. 

@eleventh19 and @ghettodev, if you could please leave questions and comments in the doc by the end of this week (9/24), then I am hoping we can have the git template honed in by the end of Sept.

**Comment by marvino3** [comment]
thank you @rjx223 for putting together a list of our [git docs for tracking](https://docs.google.com/spreadsheets/d/1JZkoZedH3m4YjYIHQvfyg4CQBpi3--HuUzc5OrUDF7A/edit#gid=0)

**Comment by marvino3** [comment]
Once the git samples are approved, we can use the [Incetivization doc](https://docs.google.com/document/d/1U51ZjwYkkZoirDm8BVhJ_gK7w7bnguNrLhdodzbvYQ8/edit#heading=h.8zo3svjrgkmg) as the initial sample to run through the git template @rjx223

**Comment by eleventh19** [comment]
@marvino3 helped create a [template for job descriptions](https://docs.google.com/document/d/1LnAanGMcOHO5NkQBEmXHonpl_t3nFkuTW_gci2FyF8A/edit#heading=h.3zn3vgvq749y), made the final updates after reviewing with @ghettodev.

**Comment by rjx223** [comment]
Folder created to organize updated Git docs: 

https://drive.google.com/folderview?id=1DfjkzhMOmqFQ6Vlft8nFyLDRUxf_lF3M

**Comment by rjx223** [comment]
Victoria, @marvino3, and @rjx223 met today and reviewed Process: Document Content Pipeline

Takeaways:
Rachel - creating rewards template, updating all reward/initiatives documents
Victoria - creating reference template, updating all reference documents 
Maria - creating job description template, updating miscellaneous documents, reviewing document updates made by Rachel and Victoria  

Regrouping next Monday

**Comment by eleventh19** [comment]
testing to see if we can add checkboxes in comments 
- [ ] create a new project card for identifying documentation that needs to be created 
- [ ] Interview team leads for missing documentation

**Comment by marvino3** [comment]
@eleventh19 updated checklist...
 
- [x] general git content creation guide
- [x] documentation process outlined
- [x] document status audit
- [x] hackmd tags updated
- [ ] create content type specific templates
- [ ] review and update each doc
- [ ] update git landing page
- [ ] update ToC 
- [ ] update process for creating new docs/ updating old docs
- [ ] ensure all docs are live (listed or unlisted) in git

**Comment by eleventh19** [comment]
reflected above

**Comment by rjx223** [comment]
@eleventh19 @ghettodev 
The SCRF Contributor Recognition and Rewards and Rewards Template are ready for approval on HackMD.

**Comment by rjx223** [comment]
Rewards Template has been recalled until @marvino3 and I hear back from various rewards content owners. Moving to draft, will update as needed.

**Comment by marvino3** [comment]
@eleventh19 @ghettodev I have incorporated comments left in the gdoc. The [SCRF Writing Style Guide](https://hackmd.io/BfwXcm07S-yFIa6mpUoE7A?both) is in HackMD and ready for final approval.

**Comment by rjx223** [comment]
SCRF Reading Group, SCRF Impact Award, & SCRF Weekly Community Calls have been updated and reviewed by their content owners. @marvino3 will review before marking them ready for approval.

**Comment by vsterling** [comment]
I will revisit the Notable Works Bounty revision after progress has been made in the project's development. Moving on to revise the Glossary Terms and create a draft Reference Template.

**Comment by rjx223** [comment]
Starting updates to Researcher Mandate & Moderator Mandate documents

**Comment by marvino3** [comment]
In the process of reviewing and updating the Git home page and Connecting w SCRF

**Comment by eleventh19** [comment]
@marvino3 @rjx223 @vsterling how far do you think we can get with the doc revision before the holidays (assuming ~2-3 new docs pop up for review)

**Comment by eleventh19** [comment]
I cleared out the docs that were listed as approved on hackmd (besides the mentorship one, which I'll explain later) and added the peer review and PM intern job descriptions to github

**Comment by vsterling** [comment]
Discussed the Reference Template and Glossary Terms with @marvino3. Both documents require a few more edits, and then I will move on to revising the remaining reference materials.

**Comment by rjx223** [comment]
The following documents are ready for approval on HackMD: 
- Connecting with SCRF
- SCRF Impact Award
- SCRF Weekly Community Calls
- SCRF Pan-African Micro-Grant Program 
- Rewards Template (please note that this appears as "SCRF Title" in HackMD)
@eleventh19 @ghettodev

**Comment by rjx223** [comment]
Transcript template is drafted. All transcripts have gone through the first round of updates. @marvino3 to review prior to HackMD conversion. @eleventh19, since you know the material best, please take a look at the first sentence in each document that describes the target audience and why someone would want to read the transcript and edit as needed. Thank you.

**Comment by rjx223** [comment]
All transcripts are ready for approval. The Transcript Template and Rewards Template are ready for approval as well.

**Comment by marvino3** [comment]
To recap: 
- We have revised and updated 20 documents, we have another 15 that are in the content review phase, and another 5 that we will need to update. 
- All of the about SCRF language will be updated once the mission/ vision language is approved. 
- In Jan, we will want to review the git home page/ ToC to determine if there are docs we want to add or remove.

**Comment by eleventh19** [comment]
@marvino3 @rjx223 @vsterling FYI I cleared out all of the approved docs on HackMD, they're live on github

**Comment by eleventh19** [comment]
I know @marvino3 and @vsterling met recently to discuss. Can you please give an update when you can on the plan going forward?

**Comment by vsterling** [comment]
@eleventh19, @marvino3 helped me get familiar with the Document Revision process from beginning to end.

Immediate Next Steps:
- Ensure all documents across GitHub, HackMD, and Google Drive are accurately represented and linked in the [Document Status](https://docs.google.com/spreadsheets/d/1JZkoZedH3m4YjYIHQvfyg4CQBpi3--HuUzc5OrUDF7A/edit?usp=sharing) tracker.
- Edit the [Documentation Pipeline](https://docs.google.com/document/d/16eROBjPWMMW36FeZ3QvNM8TM_QRixnTrLHVE63T7W-M/edit?usp=sharing) doc to reflect most up to date process.

Goals:
- Complete revision for all Live-Old docs by end of March. (First priority.)
- Maintain list of important but not urgent action items for streamlining SCRF documentation. (These items are second priority.)

**Comment by vsterling** [comment]
Created a [Documentation Strategy doc](https://docs.google.com/document/d/1A5UXpVPDM9oUnYqg4ry-BAMrNcY7aNWGh4NMFduw8j0/edit?usp=sharing), currently under revision with @marvino3. Implementing edits, adding timelines, etc. still needed.

**Comment by eleventh19** [comment]
Thanks for sharing that doc. Just wondering, what's the status of the Live-Old docs @vsterling?

**Comment by vsterling** [comment]
Done on GitHub:
- Edited and added (new) Social Media Manager JD
- Revised (live-old) How to Get Compensated for Work
- Removed (live-old) Community Lead JD

In Process:
- Editing the (new) [Project Post Template](https://docs.google.com/document/d/1z2l1QYPV1c4pWLeYznunygmBIKPyEChJEtRA_Ie4_tU/edit?usp=sharing)
- Updating (live-old) Project Manager JD
- Replacing the (live-old) [Research Improvement Proposal](https://github.com/smartcontractresearchforum/docs/blob/main/en/project_research_improvement_proposal.md) to the Project Proposal Plan Template
- Replacing the (live-old) [SCRF: Process - Research Improvement Proposal](https://github.com/smartcontractresearchforum/docs/blob/main/en/process_research_improvement_proposal.md) to the Project Proposal Process

Next To Do:
- Revise (live-old) Research Summary Grants
- Edit (new) Terms and Titles doc
- Edit (new) Guide to Creating Comments

Suggestions: Create a monthly process to ensure JDs are up to date and remove old posts.

**Comment by eleventh19** [comment]
I'm going to go ahead and close this card as it is now being managed via the [Doc Project Board](https://github.com/orgs/smartcontractresearchforum/projects/18/views/1). I think this is a reasonable place to close this issue out as doc revision will be an going function going forward and we have a mechanism in place to track new work.
