### ISSUE TITLE
Boilerplate replies for successful Post Ideas / Summary Grants

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#177]
## Description

We need consistent messaging to put in the Post Ideas section for winners and for communicating how to begin a summary.

## Workflow

- [ ] Draft docs
- [ ] Edits from Branding / Marketing 
- [ ] Ops review
- [ ] Implement

**Comment by jamesmcgirk** [comment]
[SCRF Boilerplate](https://docs.google.com/document/d/1ei9pPtHYapq9O-lILcg48PLNWgO67IcNeHUyW5UFMVI/edit#)

**Comment by jamesmcgirk** [comment]
Need to loop in Maria

**Comment by encore9870** [comment]
We don't approve new ideas this way now, unfortunately....Nice boilerplate for future references
