### ISSUE TITLE
SCRF Internal Language/Culture Exchange Project

### ISSUE THREAD

**Issue by 29988122** [smartcontractresearchforum/research_team#181]
# Project Proposal: Language/Culture Exchange

* Why’s:
    * In an async working community setting, it would be hard to keep everyone’s morale high, even harder to sync people’s vision in line with the org.
    * For a particular case observation, Taiwanese SCRF researcher occupied 10~20% of all *active* researchers, and more than half of them can’t express their thoughts fluently verbally, in English.
* Supporting Evidences:
    * In a large-scale empirical study conducted by Google’s Project Oxygen on how to improve team efficiency, mental safeness is the single most crucial key to team effectiveness and output. [REF](https://rework.withgoogle.com/guides/understanding-team-effectiveness/steps/introduction/).
    * OpenZeppelin provides “Training: Technical training, language lessons in any language of your choice.” as their employee’s benefit. Judging from this sentence only, it seems very likely that we reached the same solution to solve this team communication and culture building issue via Language/Culture/Technical exchange/training between seniors and juniors in the team. [REF](https://openzeppelin.com/jobs/opening/?gh_jid=4548720003)
* Project Goal, Qualitative Description:
    * By lighten the mood of the exchange session, we aim to achieve a positive feedback loop, in order to *train* such behavior with positive reinforcement and emotional reward, to make it persistent like a culture, and to make it scalable long-term.  \
In other words: make SCRF people happy with other SCRF people, and the snowball will get going.
    * By organizing collaborative projects with colleagues, people would *recognize* SCRF much more, thus increasing their sense of belonging. For participants, the internal cohesion would also be increased. SCRF would achieve a better output conversion rate of researchers as a result.
    * By artificially increasing people’s interaction occasions (in a remote async working setting), they are more likely to know each other on a deeper level, establishing personal/emotional connections - this could possibly ignite further research/project collaborations, not only beneficial to SCRF but also beneficial to the whole ecosystem.
* Protocol Implementation, exact steps, version 0.1, family and friend alpha:
    * Find a weekend, use Doodle(see [this](https://docs.google.com/document/u/0/d/18SnfuYAainaqezRw9RglynM37RzRG1aUXhddOYU7PvY/edit) doc to understand it) to pre-allocate slots from Fri to Mon.
    * Send invitations/DMs to potential participants, with Doodle link and Doodle hackmd instructions.
    * Monitor people’s reply and respond to them. Remind people to fill in the Doodle schedule.
    * Arrange meetings of group of 2~3, according to their available time, language pref, language ability. Larger size’s not recommended (high participation and initial impression is of utmost importance).
    * Create discord DM groups for groups. Briefly remind them to be relaxed, just simply prepare and introduce your culture/visitor spots/historical icons of your mother tongue/mother nation to each other, with frequent language tutoring. \
<span style="text-decoration:underline;">Make this the experiences of the group, do not interfere/interrupt the flow. Make it feel special to participants.</span>
    * Let them arrange the time and the length freely. (1hr default)
    * After the weekend, ask all the groups and participants with a qualitative questionnaire. Iterate this protocol as needed.
* Expected Results:
    * See Project Goal, Qualitative Description.
    * The language/culture exchange sessions can evolve to a culture itself - just jump in the discord channel, check the docs and the Doodle that weekend, and find one session to join/find a person to meet. No PM efforts needed.
* 2021/10/12, encountered problems:
    * The first week failed to be realized. People’s available timeslot diverges, limit not exist lul. See [here](https://docs.google.com/document/u/0/d/18SnfuYAainaqezRw9RglynM37RzRG1aUXhddOYU7PvY/edit).
    * Initially before culture was established, PM efforts had to be done - you just can’t have a system there and expect people to fill in and execute that willingly - not gonna happen.
        * Same, hard to pinpoint people who wants to join potentially - seems very dumb to ask/bother people one by one in DM.
    * Even if there are like..30 ppl filled in the Doodle, the algorithm to efficiently group/match people is lacking. This is crucial if we want it to be scalable and autonomous.

**Comment by 29988122** [comment]
Please refer to [this working folder](https://drive.google.com/drive/folders/1-3zoRB_BTo6cEKqFhMesg9SzDeYE4qYv) for all the documentations and protocols. Permissions are required, contact Eugene for details.

**Comment by 29988122** [comment]
Was [this issue](https://github.com/smartcontractresearchforum/research_team/issues/161), now pivoted into this exchange project.

**Comment by 29988122** [comment]
PMs are assigned to @eleventh19 @jamesmcgirk @twan-dev @LorrettaGS temporarily, until we came out a better solution to conduct the first-time-trial-run.

**Comment by encore9870** [comment]
@29988122, @LorrettaGS, and I met this week to discuss this
My meeting notes - 
### Concerns
 - Participants are not guaranteed to feel "mentally safe"
   - Introducing home culture could be even harder than making academic presentations
   - If taken too seriously it can become a challenge
 - We don't know how interested people are in the long run
   - Despite the initial hype, not enough people filled the when2meet survey, 

### Ideas
- Have a topic
  - Select a host beforehand
  - Let people know what to expect
- Keep It Voluntary
  - Name it something like "out-of-office language exchange", so people would know it doesn't go on the hour sheet
- Keep it Casual
  - Pick the time based on the host's availability
  - Don't ask for availability from everyone. Secure 1 participant and more will join if it's interesting
  - Avoid an arms race by asking people not to over-prepare. Don't create slides, worksheets, etc.

**Comment by LorrettaGS** [comment]
Created/Updated the Proposal for the SCRF: Community Passport: Language and Culture Exchange. @twan-dev and @29988122 will review and provide feedback before sending it to @eleventh19 for review.

**Comment by LorrettaGS** [comment]
@29988122 and @twan-dev reviewed the document, small updates were made and sent to @eleventh19. 

@eleventh19 will review and provide feedback. Document is available here. https://docs.google.com/document/d/1FqOCYCYea1Z8EnxyF244MCHFe-ndnF9K/edit#heading=h.bu9lkpui8kx5

**Comment by eleventh19** [comment]
Reviewed the doc and added a comment. Looks good otherwise. Feel free to tag James, Paul, and Rich to review, as well as the general PMs.

**Comment by eleventh19** [comment]
@LorrettaGS can you remind, what is the status?

**Comment by encore9870** [comment]
Current State
- A draft survey is in progress and it should be ready to hand out to community members in the coming week
- Editing project proposal to comply with RIP template

Next Steps
- Nov 10 - 13  hand out survey to all SCRF members
   - [ ] APAC call
   - [ ] All hands
   - [ ] Research mentorship
- Reach out to volunteer hosts 
- Settling a time for the first exchange

**Comment by LorrettaGS** [comment]
Thanks @twan-dev for the follow-up. I wanted to make a few adjustments to the timeline that you created. 
The draft survey and proposal will be updated and with go through review this week. I want to make sure that you and @29988122 are fine with what we pull together. Hope to also have @eleventh19 review it on Thursday, November 11th. 

During the week of November 14th the Survey will go out to SCRF Members:
- [x] November 17 - APAC Research and Community Call (Presented by @29988122 and @twan-dev)
- [ ] November 17 - All Hands (Presented by @LorrettaGS with support from @eleventh19 (if needed))
- [ ] November 18 -  America's Community Call (Presented by @LorrettaGS)
- [ ] November 20 - Research Mentorship (Presented by TBD)

@twan-dev the rest of your list still stands, I just wanted to adjust the dates. Thank you.

**Comment by LorrettaGS** [comment]
@eleventh19, our team has updated both the document and the survey and they are both in your inbox to review. I will also link the proposal here. 
https://docs.google.com/document/d/1lQNbF4WXAzHoOmZ5uH1-GIhHYcsyZseW_aAQQM3cWGE/edit#

**Comment by LorrettaGS** [comment]
During the 11/16 - 11/17 APAC Research and Community Call the survey and proposal were presented to members along with the motivations behind the project. It was also debuted on the #general and #community_passport channels.
 
During the 11/18 America's Call the project it will be presented there as well.

**Comment by eleventh19** [comment]
@LorrettaGS is there a date set for the first one or is the hope to get clarity on a date when presenting on this in the community call this week?

**Comment by LorrettaGS** [comment]
There was a slight delay presenting at the 11/18 America's call. Hope to present it to the masses on 12/2. 
Despite the delay in presenting the project to the America's community we have received 8 interested people. 

Following the 12/2 call a meeting will be scheduled with @twan-dev and @29988122 to review and discuss next steps. Hoping to move forward with this project before the holidays.

**Comment by LorrettaGS** [comment]
To follow up on the language exchange project. Information was shared during the 12/2, America's community call. During the community call 9 additional people joined bringing the total who were interested to 16 in total.

**Comment by LorrettaGS** [comment]
The team of @29988122, @twan-dev and @LorrettaGS will review and schedule meetings with hosts and help identify times to meet. 

In the meantime, a SCRF Community Passport gathering is scheduled for Saturday,December 18th at 10:00a.m. EST.

**Comment by eleventh19** [comment]
I'm going to go ahead and close this card as a meeting was held in December. once there's the desire / plan to go from the pilot to a consistent project, a new card will be opened
