### ISSUE TITLE
SCRF Directory and Who's Who Posts

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/research_team#183]
**Description**
This is an internal project to create a directory for SCRF for the Discord as well as scheduling monthly posts to announce roles and role changes.

- [ ] Create a directory
- [ ] Make directory public or public as needed
- [ ] Draft language to announce new "Core" people and point out who the community should be interacting with.
- [ ] Schedule for "Core" messages on chat

**Comment by LorrettaGS** [comment]
I am working on something similar on the Community Call document. So far I have pulled together bios which can be folded into a directory. So just flagging this for you @eleventh19 and @zubepaul

**Comment by zubepaul** [comment]
Potentially expand to a project/community roll-up of what happens as SCRF. Socials and chat news roll-up. @LorrettaGS and @nakedwinnie, this might be something the three of us coordinate. Becomes a forum post maybe?

**Comment by zubepaul** [comment]
@rjx223 is also interested in contributing to/developing the rollup on the chat. Tagging her here to make sure she gets updates.

**Comment by LorrettaGS** [comment]
@eleventh19 and @zubepaul, shared you on a quick directory proposal for current SCRF staff and willing community members.

**Comment by encore9870** [comment]
The onboarding team owns this now.
