### ISSUE TITLE
Additional revisions to calls (community, all hands, research)

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#184]
This card is meant to track the upcoming changes that we need to think through in regards to a few calls. 

Work to explore 
- [x] does it make sense to reschedule the current Wed community call to an earlier time to make it more accessible for the Taiwan-based researchers? 
- [x] do we need to add a third community call focused on being more accessible for current/potential community members in Africa and Europe?
- [ ] adding a second all-hands/research meeting to be more accessible for team members around the world

No documentation currently exists beyond what's in the [community call project doc](https://docs.google.com/document/d/18aGFdpn9GUr7TpCZsSj83ICMoXandk1HV-ZFWFBerVg/edit#)

**Comment by eleventh19** [comment]
@jamesmcgirk @twan-dev please provide an update here once you sort out the timing of the Wed community call. Let's also chat with @LorrettaGS to discuss the idea of adding a third community call in the near future.

**Comment by LorrettaGS** [comment]
@jamesmcgirk & @twan-dev I will reach out to schedule some time to connect and plan the future of Community Calls.

**Comment by jamesmcgirk** [comment]
@twan-dev @LorrettaGS we landed on 12:30am ET as the new APAC Community Call time during the meeting

**Comment by eleventh19** [comment]
I think that we can close this issue as the Wednesday call was rescheduled and we are going to set a new time for the research call so we'll see if a second one is needed
