### ISSUE TITLE
Community - trial a different cadence for the community calls

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_team#187]
After chatting with @LorrettaGS, we want to trial a different cadence for the calls. We're going to do one week project presentation and one week community/research presentation. @LorrettaGS please add the link to the planning sheet where we're planning out the next few. Hoping that the next few weeks will be (need to confirm with folks):

- crypto fixo project 
- decentralization research
- roadmap project
- TBD research
- community project proposals
- TBD research

The mentor program participants will have a chance to present to the community after the program is done. 

If anyone has ideas of who could present or if you want to present on this topic, please comment here or reach out to @LorrettaGS or me

**Comment by LorrettaGS** [comment]
Hi Team, [here is the link.](https://docs.google.com/spreadsheets/d/1IMxfFZ2N_hZVNhjxP6079qg0o0GbiJVEH_LUeKiuig4/edit#gid=1569158022)

**Comment by eleventh19** [comment]
Thanks @LorrettaGS! Do you think we need to create any process beyond discussing it and reaching out to people? Should we try to get input from the community on what they want to hear about?

**Comment by LorrettaGS** [comment]
I do think that we need some more concrete plans. @eleventh19, it might be a good idea to plan with @jamesmcgirk to see how we can plan for future Community Calls. 

Should we look to connect this week.

**Comment by zubepaul** [comment]
What is the status of this? Is this now a practice? @LorrettaGS @eleventh19

**Comment by encore9870** [comment]
I believe the link above is still active and accurate and managed by Eugene. I'll leave this ticket open for now

> Hi Team, [here is the link.](https://docs.google.com/spreadsheets/d/1IMxfFZ2N_hZVNhjxP6079qg0o0GbiJVEH_LUeKiuig4/edit#gid=1569158022)

**Comment by encore9870** [comment]
Impressive persistence...!!

**Comment by encore9870** [comment]
Closing this since it's no longer relevant. Please reopen if it's a wrong assessment!
