### ISSUE TITLE
Style Guide Revision

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/research_team#188]
The intention of this project is to review and update the style guide based on updated branding guidelines.

- [x] Update style guide
- [x] Internal review
- [x] Publish on git
- [x] Create a video

**Comment by marvino3** [comment]
Updated [SCRF Writing Style Guide](https://docs.google.com/document/d/15EVG2e5DjHXvaXXY_H48I8ENDBsKVSeCZJddp2OLMxw/edit#) in Google Docs. And the [updated guide in HackMD](https://hackmd.io/BfwXcm07S-yFIa6mpUoE7A). Sent to @jamesmcgirk, Ralph, @eleventh19, and @ghettodev. Please review to finalize and publish by EOW.

**Comment by eleventh19** [comment]
Thanks @marvino3! Will review and follow up with any questions

**Comment by marvino3** [comment]
The style guide has been approved. Need to publish it to git @eleventh19

**Comment by eleventh19** [comment]
the style guide is waiting to get approved, PR has been submitted

**Comment by eleventh19** [comment]
@marvino3 am I correct in thinking that all that's left is finalizing the video with @ivanplazacic? or is there anything else?

**Comment by marvino3** [comment]
yes, style guide has been published and video has been recorded, it is now in the final editing phases @eleventh19 @ivanplazacic

**Comment by eleventh19** [comment]
@ivanplazacic can you please give an update on the video

**Comment by ivanplazacic** [comment]
Yes. The videos are waiting for @marvino3 to approve.

**Comment by marvino3** [comment]
All approved, thanks @ivanplazacic

**Comment by ivanplazacic** [comment]
Here is the folder with the videos:

https://drive.google.com/drive/folders/1SKUz37s650A-9maT46s9sBQVavii0DBK?usp=sharing

**Comment by marvino3** [comment]
@eleventh19 is reviewing the videos

**Comment by eleventh19** [comment]
Unlisted youtube videos:
[socials](https://youtu.be/gXlvOZ1HJzg)
[longer video](https://youtu.be/F9NuQzE9F_U)
