### ISSUE TITLE
Creating a Discord Channel for the SCRF Community Passport: Language and Culture Exchange

### ISSUE THREAD

**Issue by LorrettaGS** [smartcontractresearchforum/research_team#189]
The SCRF Community Passport Language and Culture Exchange aims to create a collaborative environment to foster engagement within the SCRF’s community. This will lead to more discussions, opportunities for growth, and most importantly, it will create a space where people can share about themselves, their culture, and their identity. 
 
A dedicated Discord channel will help community members connect and enable them to share their culture and interests.

Access - This is open to the SCRF community, all those interested in the Language and Culture Exchange are invited to join

Location on Discord - Text Channels

Roles - @LorrettaGS (Project Manager) will serve as primary with @twan-dev (Project Manger) and @29988122 (Creator) serving as secondary.

**Comment by LorrettaGS** [comment]
@ghettodev, can you create a dedicated Discord channel for the SCRF Community Passport: Language and Culture Exchange. 

Some name ideas - 
Community Passport:LCE, Community Passport, Language and Culture, L & C Exchange

**Comment by LorrettaGS** [comment]
Access - This is open to the SCRF community, all those interested in the Language and Culture Exchange are invited to join - Will share on the #general channel and direct those interested to the "exchange" channel. 

Location on Discord - Text Channels

Roles - @LorrettaGS (Project Manager) will serve as primary with @twan-dev (Project Manger) and @29988122 (Creator) serving as secondary.

**Comment by ghettodev** [comment]
I've created the channel `Community Passport` and given the PM role permissions to change some admin settings. Let me know if anything looks broken.

**Comment by encore9870** [comment]
Everything so far looks great. Closing this issue since the channel is functioning well.
