### ISSUE TITLE
Create a definitions doc and get started on establishing consensus

### ISSUE THREAD

**Issue by visavishesh** [smartcontractresearchforum/research_team#19]
https://docs.google.com/document/d/1t6eg3zgwxh0w-X98sZTSN7rgGWcA5JCBPb1WNEf7zyI/edit

- [ ] Create document to define the glossary itself

- [ ] build internal consensus

- [ ] externalize definitions to github

- [ ] create references to definitions from forum

**Comment by ghettodev** [comment]
@visavishesh can you add some more detail to this ticket for me?

**Comment by jamesmcgirk** [comment]
eclipsed by Project Plan: Glossary
