### ISSUE TITLE
Task: Forum Tag Update

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/research_team#192]
**Description**
This is a task to update the forum with appropriate tags. It is a one-time task as a maintenance plan should prevent tagging from needing singular tasks in the future.

**Steps**
- [x] Create rules regarding what and how to tag
https://docs.google.com/document/d/1m7XZ6jGk2lHCQNb6HUwWZVVillD4-f3rsLJcbhb4KtU/edit#heading=h.ord54r83vyh
- [ ] Update ticket #191 to include the rules of tagging in the maintenance document and any appropriate process documents.
- [x] Identify forum posts that need tag updates
- [x] update all identified posts with appropriate tags in the GtM spreadsheet and notify Paul to do the Forum updates

[Content Team Tag list](https://docs.google.com/spreadsheets/d/1_Ug7s_ckeAsFqTnQ7SWNQ_f4NJz3dhfxbpcG0Rz4HS4/edit#gid=0)

**Comment by jamesmcgirk** [comment]
11/23 - agreed to a basic scheme for tagging, red = suggested deletion; bold = suggested addition; PROPOSED: a suggested addition to our tags

**Comment by zubepaul** [comment]
Things to do next:
- Bring up Engagement process as Engagement Review task for tags
- Moderation has say on the tag application (up to 4) based on glossary
- Remove mistagged content on the forum using work on the GTM spreadsheet.

**Comment by ralphlombreglia** [comment]
1) To my knowledge, we haven't created rules for tagging. I would like to understand and participate in the process for doing that. Some obviously necessary tags are missing.
2) I went through approx. 25 3-level posts and recommended obvious additions, and in a few cases deletions, of tags. Approx. 60 3- and 40-level published posts remain. I'm getting faster, so I estimate 2-3 hours to finish this. 
3) Then the last step is to install/delete the recommended tags. I don't think I have the power to do that.

**Comment by zubepaul** [comment]
One round of forum tag updating is completed.

**Comment by ralphlombreglia** [comment]
As of 2021.12.17, the tag survey is complete. See the GtM spreadsheet for updates and deletes in all categories:
- Auditing and Security
- Oracles and Data
- Consensus
- Scaling
- Mechanism Design and Game Theory
- Cryptography
- Tooling and Languages
- Privacy

**Comment by encore9870** [comment]
Important project! This is now tracked in smartcontractresearchforum/core-projects#31. Closing this so we keep the conversation in one plan.
