### ISSUE TITLE
Project: Christmas reunion for SCRFers in Taiwan

### ISSUE THREAD

**Issue by Astridchou** [smartcontractresearchforum/research_team#201]
For increasing team spirit and the sense of community, SCRFers in Taiwan reunion together to have a Christmas dinner, exchange our feeling and thoughts about SCRF, collect constructive reflection.

1. Time: 12/18 (Sat) 16:00 - 21:00
2. Attendance
- 12 people confirmed: Astrid, Twan, Sean, Seth, Jerry, Eason, Tony, Colin, Bill, Cindy, Moven, Mark, 
- 2 people maybe: Winson, Jason
3. Location: Christmas town in New Taipei City
4. Activities  
- Eating dinner together
- Secret Santa
- Exploring Christmas town
- SCRF Christmas-themed prize
  > Discuss projects
  > Increase team spirit, sense of community
5. Group Pictures

**Comment by Astridchou** [comment]
https://docs.google.com/document/d/1oOe5AhoMmZpF_Mjb-PXbJESaksUyPwvaFwaNmG8lq70/edit

Invoice and picture

**Comment by encore9870** [comment]
Closing since completed
