### ISSUE TITLE
Task: Register "scrf.io" and "scrf.info" as Alternative Domain Names.

### ISSUE THREAD

**Issue by ralphlombreglia** [smartcontractresearchforum/research_team#203]
"scrf.io" presently available for one year for $45 (pairdomains.com) and $60 (godaddy.com); "scrf.info" for $2-3 at the same registrars.

**Comment by SirAh0** [comment]
We need scrf.io for social media. How can we elevate this to procurement?

**Comment by SirAh0** [comment]
SCRF now owns scrf.io

We can close this task.
