### ISSUE TITLE
Streamline Notable Works project and pipeline

### ISSUE THREAD

**Issue by vsterling** [smartcontractresearchforum/research_team#204]
Before the Bounty Program (Issue smartcontractresearchforum/operations#45) is further developed, the Notable Works project and content pipeline requires organization and streamlining. There is inconsistency across multiple documents and an unclear process overall.

Steps:
- [ ] Outline Notable Works pipeline process
- [ ] Address issues and inconsistencies
- [ ] Update all documentation

**Comment by encore9870** [comment]
Looks like this is tracked in the messaging board and this ticket is no longer relevant.
