### ISSUE TITLE
Finish Audit Summary Template

### ISSUE THREAD

**Issue by visavishesh** [smartcontractresearchforum/research_team#22]
Current template is at our shared drive: https://docs.google.com/document/d/1oAni0ibN2kmKYtTphNfGF683aOyp5BfK_1iqgKMkUf8/edit?usp=sharing

TODOs in the document remain:

- [x] Decide whether to include "Mitigations and Follow-ups" section, and if, so under what format
- [x] Decide whether to include "Applicability section", and if, so under what format

**Comment by ghettodev** [comment]
@lpassos @visavishesh can we get a description and a link to a doc here?

**Comment by lpassos** [comment]
Current template is at https://docs.google.com/document/d/1oAni0ibN2kmKYtTphNfGF683aOyp5BfK_1iqgKMkUf8/edit?usp=sharing

TODOs in the document remain:

- [ ] Decide whether to include "Mitigations and Follow-ups" section, and if, so under what format
- [ ] Decide whether to include "Applicability section", and if, so under what format

**Comment by lpassos** [comment]
@ghettodev Added
