### ISSUE TITLE
Onboarding Content for Chat (Discord) Go Live

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/research_team#229]
https://docs.google.com/document/d/1rX2Yzua2BaDn6MJqukC1FKvzEUi9yfbO/edit#heading=h.1fob9te

- [x] 🏁-start-here content: Welcome, Useful Links, FAQ, Unlock Server

- [x]  review 📘-directory-faq descriptions for each channel.

- [x]  Bot Message To New Users

- [x]  Pinned Messages.

**Comment by zubepaul** [comment]
@brianalexakis @eleventh19 
Is this task finished? Should we close this ticket?

**Comment by vincenzospaghetti** [comment]
@SirAh0 how do we close this? I'm making a new one

**Comment by SirAh0** [comment]
Thanks for pinging me, I've closed the issue. If you cannot close issues and think you should be able to do so, feel free to open an IT request issue for 💾 GitHub Teams
https://github.com/smartcontractresearchforum/IT/issues/new/choose
