### ISSUE TITLE
SourceCred Launch

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/research_team#235]
[🔗](https://emojipedia.org/link/) [SourceCred Project Plan Doc](https://docs.google.com/document/d/1I09x7UweBXngtjK-fBH6ZunVrJqybfkDtEV2hrj634Y/edit?usp=sharing)
- [x] Update Project Plan - New Forum Topic - Poll Post section
- [x] Make Forum Post
- [x] Link forum post back to this issue as a comment

[🔗](https://emojipedia.org/link/) [Chat Project Plan](https://docs.google.com/document/d/1c5EhvYxpSyNuZZv0fX-KTmDv1OtawzWV/edit#)
- [x] Update Phase Two - IT requirements

[🔗](https://emojipedia.org/link/) [Chat Channels & Content](https://docs.google.com/document/d/1rX2Yzua2BaDn6MJqukC1FKvzEUi9yfbO/edit#)
- [x] define 💲sourcecred-opt-in messaging

[🔗](https://emojipedia.org/link/) [Chat Phase Two - IT Go Live](https://docs.google.com/document/d/1FkM5EOugskHan6NOGCCTvVmkwLIjU6buBfdJL6ENsMg/edit#heading=h.ipetpl3qxb4i)
- [x] checklist to include changes needed for Opt In

- [x] SourceCred Resouce Pack @SirAh0 

- [x] Determine Cred -> Dai Monthly Build Process @SirAh0 @ghettodev

**Comment by zubepaul** [comment]
[Forum post](https://www.smartcontractresearch.org/t/sourcecred-polls-and-first-implementation/1477) is up. Polls added in the morning. Also was able to link the the poll post to the earlier discussion post.

**Comment by SirAh0** [comment]
Project Plan updated with all details.
