### ISSUE TITLE
Chat - Phase Two - Onboarding Go Live

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/research_team#237]
[🔗](https://emojipedia.org/link/) [Chat Roles](https://docs.google.com/document/d/1EUnK3UliHp-p6CXs9dp4mwkT2qSCXyuA/edit?usp=sharing&ouid=107935953561747433773&rtpof=true&sd=true)
- [x] define onboarding roles 
- [x] roles on test server

[🔗](https://emojipedia.org/link/) [Chat Channels & Content](https://docs.google.com/document/d/1rX2Yzua2BaDn6MJqukC1FKvzEUi9yfbO/edit?usp=sharing&ouid=107935953561747433773&rtpof=true&sd=true)
- [x] update H1 and H2 to match test server room list
- [x] add/edit content for each onboarding channel
- [x] update the main start-here channel content

[🔗](https://emojipedia.org/link/) [Chat Project Plan](https://docs.google.com/document/d/1c5EhvYxpSyNuZZv0fX-KTmDv1OtawzWV/edit?usp=sharing&ouid=107935953561747433773&rtpof=true&sd=true)
- [x] provide an overview of the changes being made in the Phase Two - Onboarding section

[🔗](https://emojipedia.org/link/) [Chat Phase Two - Onboarding Go Live Steps](https://docs.google.com/document/d/1FkM5EOugskHan6NOGCCTvVmkwLIjU6buBfdJL6ENsMg/edit?usp=sharing)

- [x] Go Live checklist

**Comment by vincenzospaghetti** [comment]
Changes to Discord 5/17:
- [ ] Additional changes to channels to streamline channels and combine duplicates (only for onboarding)
- [ ] changing "Earn-with-Scrf" category to "Opportunities"
- [ ] Changing "Opportunities" category to read-only information kiosk
- [ ] Creating final ticket and moving from test net to live server @ghettodev - dependent task
- [ ] Make SCRF Live voice channel live and active for use
- [ ] Move onboarding meeting bot into existing "Events" channel
- [ ] Change "Onboarding" category to "Apply Here" category
- [ ] Update project plan docs @SirAh0 
- [ ] Text adding to each channel for onboarding: https://docs.google.com/document/d/1qBsB5g4YXjY1tBH6ZKb6GvX3dv-d4Az2zMG5UBVdqkc/edit?usp=sharing. Need input from @marvino3 and team

**Comment by vincenzospaghetti** [comment]
Targetting EOD FRIDAY 5/20 for Live Onboarding with New process and text on the server!

**Comment by vincenzospaghetti** [comment]
Adding New changes in Discord/Chat (to be rolled out on the new discord change cadence that we are actively establishing):

- [ ] Roles https://docs.google.com/spreadsheets/d/1biVGofWdECcfVezXmGKk0mWIicotN6ztjyrwytLK3kg/edit#gid=0
- [ ] Bot for Start Here Information https://github.com/CommonsBuild/onboarding-bot
- [ ] Bot for introductions

**Comment by SirAh0** [comment]
Changes for Chat are now handled via the [Project Board](https://github.com/orgs/smartcontractresearchforum/projects/31) and [New Issue Forms](https://github.com/smartcontractresearchforum/engagement/issues/new/choose)
