### ISSUE TITLE
Chat - Phase Two - Discovery Go Live

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/research_team#238]
[🔗](https://emojipedia.org/link/) [Chat Project Plan](https://docs.google.com/document/d/1c5EhvYxpSyNuZZv0fX-KTmDv1OtawzWV/edit?usp=sharing&ouid=107935953561747433773&rtpof=true&sd=true)
- [ ] Provide requirements in Phase Two - Discovery section

[🔗](https://emojipedia.org/link/) [Chat Channels & Content](https://docs.google.com/document/d/1rX2Yzua2BaDn6MJqukC1FKvzEUi9yfbO/edit#)
- [ ] Add content to Discovery channels

[🔗](https://emojipedia.org/link/) [Discord Chat Roles](https://docs.google.com/document/d/1EUnK3UliHp-p6CXs9dp4mwkT2qSCXyuA/edit?usp=sharing&ouid=107935953561747433773&rtpof=true&sd=true)
- [ ] Add new Discovery user roles

[🔗](https://emojipedia.org/link/) [Go Live Checklist](https://docs.google.com/document/d/1UeZBTB0z-pG4nVGUoaQKqGjHIrHDwTNpFRavKhAf1Es/edit?usp=sharing)
- [ ] Complete check list

**Comment by encore9870** [comment]
All done super old - Brian
