### ISSUE TITLE
Calendar and Events Wrangling

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/research_team#240]
### Moved to Project Board and Repo
[SCRF Calendar of Events](https://github.com/orgs/smartcontractresearchforum/projects/30)

[📅 Add New Event](https://github.com/smartcontractresearchforum/discovery/issues/new/choose)

This ticket is now closed.

---

### Submitting New Calendar Events
Please reply below as a comment filling out as much as you can:
```
Title
Start Time (PDT/PST)
Cadence
Duration
Attendees
Location (url)
Description
```

### Current Tasks
🔗[SCRF Calendar and Events Project Plan](https://docs.google.com/document/d/1WEW0Unw_X_xtpAAcYpl7NZqbRkhRKgC0PYN4sxYpsD8/edit?usp=sharing)
- [ ] build project plan @SirAh0 

**Chat**
- [x] Get sesh bot posting weekly events again @SirAh0 

**Calendar**
🔗[SCRF Events Tracking Spreadsheet](https://docs.google.com/spreadsheets/d/1TL2j5mz4v9QiaIooCJXFB6iY1YAnaAm1t3bKu-uiPe8/edit?usp=sharing)
- [ ] new gcal under it@scrf.io @SirAh0 
- [x] #242
- [ ] scrub old gcal URLs with new in SCRF documents

**Comment by vincenzospaghetti** [comment]
@SirAh0 Need a calendar reminder for Onboarding meeting:

Title: "Monthly Onboarding Session"
Time: Noon MTN/2 PM EST
Duration: 30 minutes
Attendees: Open to All; Mandatory for new SCRF contractors
Location: #Onboarding LIVE channel

Description: This is the monthly onboarding meeting for SCRF. If you have recently been hired, are new to SCRF, or are looking for opportunities, please attend this meeting. Optional for internal SCRFers. 
Day: 6th day of every month. if the 6th falls on a weekend, add it to the next US business day.

**Comment by vincenzospaghetti** [comment]
@SirAh0 Need a calendar reminder for submitting time:

Title: "REMINDER: Final Day to Submit Invoice Hours on Request Finance"
Date: Every month, 2 days before end of month.
TIme: 8 AM MTN/10 AM EST
Duration: 15 min
Attendees: All Internal
Location: SCRF Live
Description: This is your reminder to submit hours to Request Finance for the last month. Invoices must be submitted no later than 2 days before the end of the month. If you are not sure how to submit hours or have questions, please join for this 15 min meeting to get questions answered. Attendance is fully optional.

**Comment by SirAh0** [comment]
> @SirAh0 Need a calendar reminder for Onboarding meeting:
> 
> Title: "Monthly Onboarding Session" Time: Noon MTN/2 PM EST Duration: 30 minutes Attendees: Open to All; Mandatory for new SCRF contractors Location: #Onboarding LIVE channel

On which day does this event occur?

**Comment by zubepaul** [comment]
@SirAh0 Need a calendar reminder for SourceCred Committee
Title: SCRF SourceCred Community Committee
Date: 2nd Friday of every month
Time: 10am PDT
Duration: 50 Minutes
Attendees: Members of the SourceCred Committee. 
Location: meet.google.com/zar-oyrc-xko
Description:
This is the monthly meeting of the SourceCred Community Committee. In this meeting, we discuss the current implementation of SourceCred nodes and edge weights throughout SCRF and also the budget and allocation mechanisms.

**Comment by SirAh0** [comment]
> @SirAh0 Need a calendar reminder for SourceCred Committee Title: SCRF SourceCred Community Committee Date: 2nd Friday of every month Time: 10am PDT Duration: 50 Minutes Attendees: Members of the SourceCred Committee. Location: meet.google.com/zar-oyrc-xko Description: This is the monthly meeting of the SourceCred Community Committee. In this meeting, we discuss the current implementation of SourceCred nodes and edge weights throughout SCRF and also the budget and allocation mechanisms.

It's been added and will rotate on the Chat calendar bot.

**Comment by SirAh0** [comment]
> 

It's been added thank you!

**Comment by SirAh0** [comment]
> @SirAh0 Need a calendar reminder for submitting time:
> 
> Title: "REMINDER: Final Day to Submit Invoice Hours on Request Finance" Date: Every month, 2 days before end of month. TIme: 8 AM MTN/10 AM EST Duration: 15 min Attendees: All Internal Location: SCRF Live Description: This is your reminder to submit hours to Request Finance for the last month. Invoices must be submitted no later than 2 days before the end of the month. If you are not sure how to submit hours or have questions, please join for this 15 min meeting to get questions answered. Attendance is fully optional.

It's been added thank you

**Comment by SirAh0** [comment]
**Title**  SourceCred Community Committee
**Start Time (PDT/PST)** 10:00 AM
**Cadence** Monthly - 2nd Friday
**Duration** 1 Hour
**Attendees** Community 
**Location (url)** [meet.google.com/zar-oyrc-xko](http://meet.google.com/zar-oyrc-xko)
**Description** 
SourceCred has arrived at SCRF.

Come join the community and share your voice!

Topics include: 
Changing Node and Edge Weights
Adjusting DAI Disbursement
Effects of SourceCred on the SCRF Forum Community
Open forum to submit ideas, concerns or other opinions

**Comment by vincenzospaghetti** [comment]
Need SCRF Live voice channels made available. In the meantime need these details added to the Calendar invite for "Onboarding Info Session/Meeting". @SirAh0 

> Onboarding Info Session
> Monday, June 6 · 12:00 – 1:00pm
> Google Meet joining info
> Video call link: https://meet.google.com/sbs-ckpi-ohk

**Comment by eleventh19** [comment]
Let me know if anything is needed from me before getting the community calls over to a new invite (maybe we can coordinate shortly after this community call?). I need to send it directly to a few folks

**Comment by vincenzospaghetti** [comment]
@SirAh0 is this project plan to create a new calendar? Or should we keep using this just for requesting events that need calendar invites on Discord/Chat?
