### ISSUE TITLE
shut down old calendar @eleventh19

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/research_team#242]

**Comment by vincenzospaghetti** [comment]
@eleventh19 we just discussed this breifly with @SirAh0. It would be closing down of this one correct? https://calendar.google.com/calendar/u/0/embed?src=c_45nqubmu17kcm9r1p8o5sqtte0@group.calendar.google.com

**Comment by SirAh0** [comment]
Correct, please see for more info
https://github.com/smartcontractresearchforum/research_team/issues/253
