### ISSUE TITLE
SourceCred - Phase Two

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/research_team#244]
**[🔗](https://emojipedia.org/link/)[SourceCred Project Plan](https://docs.google.com/document/d/1I09x7UweBXngtjK-fBH6ZunVrJqybfkDtEV2hrj634Y/edit#)**

- [ ] SCRF Community Call - SourceCred Update: Write Script @zubepaul 
- [x] Submit The Community Committee Meeting to #240  @SirAh0

**Comment by encore9870** [comment]
I believe SCRF Sourcecred is now up and running and community-driven. Updates are in the engagement repo (the latest meeting being smartcontractresearchforum/engagement#39). Good progress.
