### ISSUE TITLE
root readme for the SCRF Org

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/research_team#248]
### Related Tasks

Start Here Branding
https://github.com/smartcontractresearchforum/engagement/issues/20

Org ReadMe #115
https://github.com/smartcontractresearchforum/discovery/issues/115

---

**Comment by SirAh0** [comment]
@zubepaul

**Comment by encore9870** [comment]
Actual work is done in the above mentioned tickets. Closing this.
