### ISSUE TITLE
team creates process for adding new events to calendar - @zubepaul suggested this have a clear path for community members to add events.

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/research_team#254]

**Comment by SirAh0** [comment]
Please see the [SCRF Calendar Project Plan](https://docs.google.com/document/d/1WEW0Unw_X_xtpAAcYpl7NZqbRkhRKgC0PYN4sxYpsD8/edit?usp=sharing)

and new issues can be submitted via the [Discovery repo issues - 📅 Add New Calendar Event](https://github.com/smartcontractresearchforum/discovery/issues/new/choose)

**Comment by encore9870** [comment]
Seems finished!
