### ISSUE TITLE
Job Creation Board 

### ISSUE THREAD

**Issue by ttaloute** [smartcontractresearchforum/research_team#256]
**Project Description**

The aim of this board is to support team heads and leads looking to add new roles to their teams and projects. It will include a templated guide for scoping a role, streamline approvals from operations, track jd creation and posting. There is an intermediary step in the docs board.

* Work Plan:*

- [ ] confirm board design and function
- [ ] create a board
- [ ] test a job creation card in the board
- [ ] make any necessary mods to the process and board

### Resources

- Project Proposal: (https://docs.google.com/document/d/1kfb9oa7UsKI0rGw19HqPqQ8Zbzr5eSOCt-IU3ThrEVw/edit#)
- New Role Scoping Template (https://docs.google.com/document/d/1whK2If1FmwCbjw3rdpVLPhMRiQutwtOug6kDK5so2BY/edit)

**Comment by SirAh0** [comment]
One thing to also consider when forming a new board are the issue templates that might feed information into the board. 

Feel free to reach out to me and we can go over this topic.

**Comment by ttaloute** [comment]
Thank you @SirAh0 . I met with @twan-dev to modify the existing hiring board to have this job creation function. An issue template would be very helpful to incorporate. Twan and I already started thinking about what that could look like and if its possible to have a card move to the next column with certain activities. Apologies @twan-dev if im not explaining that right.

**Comment by SirAh0** [comment]
Issue templates are for collecting data from people who want to create new issues.

Rather than having just a blank box, you can specify what kind of data you need from them and provide instructions or context they should know about. 

Feel free to open an Issue on the IT Help Desk and we can schedule a time to talk about it. 

https://github.com/smartcontractresearchforum/IT/issues/new/choose

**Comment by encore9870** [comment]
Job creation board is now created and used ([here](https://github.com/orgs/smartcontractresearchforum/projects/33)).
