### ISSUE TITLE
Project: Build Moderator Playbook

### ISSUE THREAD

**Issue by ericjaurena** [smartcontractresearchforum/research_team#34]
### Description

We need a doc that captures best practices for existing moderators and allows us onboard new mods. Once we are finished the first draft it needs to get published in the repo for public consumption.

### Deliverables

- [x] [Moderator Playbook Draft](https://docs.google.com/document/d/190rBZGylcaHBojMSMm-ZfIxPdLxzKv2I1G1zLjIhzfk/edit#heading=h.ujjvwbujjbt6)
- [x] Public markdown version

**Comment by jamesmcgirk** [comment]
assigned to Paul Z, who presented this on 3/10/2021

**Comment by jamesmcgirk** [comment]
Moved to in progress as version 1 is in use

**Comment by zubepaul** [comment]
Working on version 2 in preparation for public markdown release.

**Comment by zubepaul** [comment]
Discuss public nature of this document

**Comment by zubepaul** [comment]
Playbook and Workflow separated. Playbook ready for review and edits @jamesmcgirk @visavishesh

**Comment by zubepaul** [comment]
Playbook is ready for final review
@jamesmcgirk @ghettodev @visavishesh

**Comment by zubepaul** [comment]
Playbook ready for public markdown version
@jamesmcgirk @ghettodev

**Comment by eleventh19** [comment]
@ishgun178 is this being converted to .md?

**Comment by zubepaul** [comment]
@eleventh19 This is converted to .md and is being updated in the other ticket associated with moderation materials

**Comment by eleventh19** [comment]
Needs to be approved in hackMD

**Comment by zubepaul** [comment]
Update this so that it includes forum maintenance tasks and making sure that the content types are accomplishing what they are accomplishing.

**Comment by zubepaul** [comment]
Playbook needs updating to include tagging and links to tag index

**Comment by zubepaul** [comment]
Waiting on Template.

**Comment by eleventh19** [comment]
@marvinok3 and @Rjx223 reviewing as part of #173

**Comment by zubepaul** [comment]
Break-out with Engagement team to update and create as a best practices document.

**Comment by zubepaul** [comment]
This issue is now also being reviewed and tracked using https://github.com/smartcontractresearchforum/discovery/issues/130

**Comment by encore9870** [comment]
This is captured and owned by Paul and his team now. Closing.
