### ISSUE TITLE
Project Plan: Business/Economics Case Study

### ISSUE THREAD

**Issue by tjd233** [smartcontractresearchforum/research_team#41]
Project outline for developing a robust academically focused business/economics case study format researching how blockchain implementation may benefit traditional/emerging business models. 

SCRF PRIMARY RESEARCH PROJECT.

Link to project plan outline: draft 1
https://docs.google.com/document/d/1HVjLNR-jNJulqIMQWYmNDzOdWDfKJiTZsKA2HMUZitU/edit#

**Comment by jamesmcgirk** [comment]
I would like to adopt this one if possible

**Comment by jamesmcgirk** [comment]
@eleventh19 - this might be a good project for me to work on with Ralph if he's coming onboard

**Comment by jamesmcgirk** [comment]
I'd like to revive this one as a project, possibly something i could do with Ralph

**Comment by jamesmcgirk** [comment]
@RalphL reviewed Trent's plan, made editorial suggestions. @jamesmcgirk to follow up this coming week.

**Comment by jamesmcgirk** [comment]
Eugene: Is this another content type that anyone can pitch or should it have a separate grant structure... how are we incentivizing this? Rich: there has be an expectation that people will do this // Empirical critique of negative results, how do we create a narrative about them?

**Comment by jamesmcgirk** [comment]
Assess after review with Ralph, get buy-in from researchers

**Comment by jamesmcgirk** [comment]
Former Consensys exec responded to an old request about some projects in Dubai -- could make a good first case study. Will discuss with Ralph. Would be great having an example of qualitative case study to use as a model

**Comment by encore9870** [comment]
This is a good plan and we are planning how to use the case study template for other programs (starting with PAG). Closing since the ticket itself is no longer relevant.
