### ISSUE TITLE
Project Plan - Use Cases

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#47]
Use Case project plan will outline how the Use Case content type will work and how they'll go through the editorial process. 
https://docs.google.com/document/d/1Nsz_SBKor4gUMTU26YwXrFArEzwV9DG9mW6D38TCyxI/edit

**Comment by jamesmcgirk** [comment]
https://docs.google.com/document/d/1ddH65uj-UMbFfhMvq4VggILOjwOOcLG14CJqkJbPXx8/edit#heading=h.olp5h2b2zw1u

**Comment by jamesmcgirk** [comment]
This issue is redundant @visavishesh am I okay to close this issue? Rich created another with the checklist

**Comment by encore9870** [comment]
This is a good plan and we are planning how to make use case template for other programs (can go through content pipeline etc.). Closing since the ticket itself is no longer relevant.
