### ISSUE TITLE
Create Document Process Workflow -

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#50]
https://docs.google.com/document/d/1jNYj09wOLfbqBgu_5mYrsPUQVSeY4qt8CnqGLcjZ3rM/edit

Need definitive guide to publishing process, what happens when things don't meet standards, who does what

Owner in charge of everything, should there be one person who is the project manager? Who owns the process?

**Comment by ghettodev** [comment]
Can you update that link? It points to the `SCRF: Project Plan - One Pagers`
