### ISSUE TITLE
Project: Identify 100 university blockchain clubs

### ISSUE THREAD

**Issue by tjd233** [smartcontractresearchforum/research_team#74]
Identify 100 university blockchain clubs. Inventory the university, club name, region, country, contact status, email(s), who is contacting them, and engagement status.

Focusing on all regions (NA, SA, Africa, Europe, ME, Oceania, Asia).

**Comment by bbeats** [comment]
Groups like [BAF](https://www.blockchainacceleration.org/) and [BEN](https://blockchainedu.org/) have tried building such networks (to my knowledge BAF is doing a better job right now). I know the folks running BAF if we want to speak to them again about collaborating.

This could also be an easy intern summer project - hire an undergrad student to map this out and do initial outreach

**Comment by ghettodev** [comment]
Let's follow up on this. I know BEN and I've had a few calls with BAF. We have the grants program is ready for some additional pilots I think.

**Comment by tjd233** [comment]
I did put together a list of 80+ university clubs/orgs for this specific project. You can find it on the google drive. Feel free to reach out if you have any questions.

**Comment by eleventh19** [comment]
This is the [current list](https://docs.google.com/spreadsheets/d/1uE4uxHvG-p49c6poQjmbC-r-WJfJkUfp5zgBCiczXFE/edit#gid=0) of clubs. This project is going to be rolled into #169 but will keep this card open until we feel we feel the list is updated to reflect this academic years landscape

**Comment by jamesmcgirk** [comment]
A quick glance suggests that we should probably be contacting these clubs via Twitter DM / Instagram rather than chasing down old members

**Comment by encore9870** [comment]
Seems that from the conversation on the above-mentioned ticket, university outreach will not be a separate outreach plan from general outreach.
