### ISSUE TITLE
Project Plan: Summaries of Paywalled Content

### ISSUE THREAD

**Issue by cipherix** [smartcontractresearchforum/research_team#78]
**Description**

Several high-profile industry publications live behind paywalls, on platforms such as ACM, ieeexplore.ieee.org, EDANZ, Springer, amongst many others. In fact, 13.2% of papers that would have made it to Research Pulse in the month of March were excluded due to subscription requirements. Unfortunately, directly hosting these papers would certainly entail legal ramifications. 

There are ways, however, where we could bring more awareness to paywalled research while minimizing legal risks. Research Summaries are the perfect format for that as they synthesize content and grant the community indirect access to research that would otherwise fall into obscurity. Institutional accounts for these publications are needed so that the Research Team can have access to these papers for the creation of summaries.

**Work Plan**

- [x] Research Publications
- [x] Purchase Subscriptions
- [x] Onboard Team

**Resources**

Project Plan: https://docs.google.com/document/d/1FMDo1BQHHZiBycom4I0ewQARCYbJo42NI-eGgf3dZTY/edit?usp=sharing

**Comment by ghettodev** [comment]
We have a subscription with Springer. IEEE is a bit of a pain and may take longer. 

As we have a framework to provide researchers with journal access let's consider this done for now.
