### ISSUE TITLE
Review Document Pipeline Process

### ISSUE THREAD

**Issue by visavishesh** [smartcontractresearchforum/research_team#8]
https://docs.google.com/document/d/1NJW2raIP384BVhG_l_LTevlESw2Uj6rUmslNc70b6E8/edit

**Comment by ghettodev** [comment]
https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1NJW2raIP384BVhG_l_LTevlESw2Uj6rUmslNc70b6E8%2Fedit

**Comment by ghettodev** [comment]
Approved
