### ISSUE TITLE
Process Improvement: Roles and Expertise

### ISSUE THREAD

**Issue by visavishesh** [smartcontractresearchforum/research_team#88]
Work with engagement to create team contact & expertise signups (potentially merge with badges)

- [ ] Expertise for use by engagement team
- [ ] Specific expectations of researchers: engagement on existing summaries/discussions, peer reviews, post-ideas, engagement/feedback on post-ideas, content for outreach (social, amas, interviews, etc)
- [ ] Process for engagement to coordinate getting resources/content for engagement on existing posts

**Comment by encore9870** [comment]
This ticket is no longer relevant. Let me know if we should not be closing it!
