### ISSUE TITLE
Content Moderation Workflow

### ISSUE THREAD

**Issue by visavishesh** [smartcontractresearchforum/research_team#95]
[Integrated](https://docs.google.com/document/d/11S6Tf1aIJh8jobhZFR9QcCyAQAnxEHFYW0-NtcNVzj4/edit#)

[Moderation](https://docs.google.com/document/d/190rBZGylcaHBojMSMm-ZfIxPdLxzKv2I1G1zLjIhzfk/edit)

**Comment by zubepaul** [comment]
@visavishesh @jamesmcgirk
Engagement edits and comments made on the Integrated workflow file. Please review/edit

**Comment by zubepaul** [comment]
Refined Moderation Workflow ready for usability review. 
File below, please update ticket with a link

@visavishesh @jamesmcgirk

https://docs.google.com/document/d/1dhQssyGpi2NarlpuN7wDgylUvnjUHa63kO3tao88oCs/edit

**Comment by zubepaul** [comment]
@visavishesh @jamesmcgirk @ghettodev @eleventh19 
Edits completed and ready for additional round of review for Moderation Workflow (link in the comment above)

**Comment by zubepaul** [comment]
Both the moderation workflow and moderator playbook are in HackMD. @jamesmcgirk and @ghettodev, could you please look at these for tone from a perspective of them being outword facing documents?

**Comment by ishgun178** [comment]
I have suggested some edits to the [Moderation Workflow on HackMD](https://hackmd.io/9NgehLoXS--WU6ZSW6K2gg) and the [Moderator Playbook on HackMD](https://hackmd.io/Vh2sYc20SbaxsEgUG-Hn4w) based on the style guide.

**Comment by zubepaul** [comment]
Edits have been made except for the edits that cross both Moderator and Researcher Playbook.

**Comment by eleventh19** [comment]
Needs to be approved in hackMD

**Comment by zubepaul** [comment]
Moderation workflow is blocked by [Moderation Playbook](https://github.com/smartcontractresearchforum/research_team/issues/34) as links in the Workflow refert to the Moderation Playbook.

**Comment by eleventh19** [comment]
@zubepaul will take a look at the doc and @marvinok3 and @Rjx223 will review as part of updating HackMD docs

**Comment by eleventh19** [comment]
@vsterling @marvino3 @zubepaul @twan-dev is this a live doc / is work on this being captured elsewhere?

**Comment by zubepaul** [comment]
@eleventh19 This is a live doc. I believe it is currently in HackMD, not the Google docs above as the "in progress" version. I think there is good reason to keep each process as its own process, however, so I will make sure to take the engagement content out and work on links instead of integrations.

**Comment by encore9870** [comment]
Closing this ticket as it is now tracked somewhere else. I DM stakeholder (Paul) and this was the response
> As for the workflow ticket, that can also be closed. It is a culmination of some of the moderation tickets and will be revised and go into the Moderator Playbook issue instead.
