### ISSUE TITLE
Project: SQAI Conference Funding

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#97]
Symposium for Quantum Artificial Intelligence

Seth is proposing a small grant to sustain their Quantum Blockchain Club during their first conference.

potential - a video presentation, a brief presentation, appearance on a poster, recruitment for potential researchers = benefit for SCRF

**Comment by jamesmcgirk** [comment]
@ghettodev would you like me to work on this with Seth? (First step would be putting together a RIP)

**Comment by ghettodev** [comment]
I don't think it's necessary for a sponsorship. I've asked @Gearlad to share a doc with me that has information about the request.

**Comment by jamesmcgirk** [comment]
Gearlad reports: . We'll have the recorded conference uploaded to Facebook and I'll send it. It will be fully held in webinar format on 5/20 and 5/29 (Taiwan's regulations for covid were just ameliorated yesterday, so now it will be fully online).

**Comment by jamesmcgirk** [comment]
Moving to Completed.
