### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by visavishesh** [smartcontractresearchforum/research_team#99]
Project Description
Roles and responsibility breakdowns for badges for SCRF team members and ecosystem participants. 

Work Plan
Enter the steps as reflected in your Work Plan:

- [ ] Develop proposal for badges

General Tips
SCRF Research Improvement Proposal
SCRF Research Improvement Process
Provide updates to this ticket at regular intervals. These tickets need to represent an accurate audit trail while contributing to the institutional record of SCRF.

Ensure the correct tags and projects have been selected in the sidebar -->

**Comment by encore9870** [comment]
This will be a shared plan C+D+E develop down the road. I've created a new issue at smartcontractresearchforum/core-projects#85 so it's easier to maintain
